# Generated by Django 4.2.8 on 2025-11-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPSqueezeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='交易对')),
                ('interval', models.CharField(max_length=10, verbose_name='时间周期')),
                ('analyzed_at', models.DateTimeField(db_index=True, verbose_name='分析时间')),
                ('klines_count', models.PositiveIntegerField(verbose_name='K线数量')),
                ('squeeze_active', models.BooleanField(help_text='是否处于有效的盘整状态', verbose_name='Squeeze有效')),
                ('squeeze_consecutive_bars', models.PositiveIntegerField(help_text='连续满足Squeeze条件的K线数量', verbose_name='连续K线数')),
                ('reliability', models.CharField(choices=[('high', '高'), ('low', '低')], max_length=10, verbose_name='可靠度')),
                ('val', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='支撑位(VAL)')),
                ('vah', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='压力位(VAH)')),
                ('vpoc', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='成交量重心(VPOC)')),
                ('hvn_data', models.JSONField(default=list, help_text='高成交量价格区间列表', verbose_name='高量节点(HVN)')),
                ('lvn_data', models.JSONField(default=list, help_text='低成交量价格区间列表', verbose_name='低量节点(LVN)')),
                ('price_min', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='最低价')),
                ('price_max', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='最高价')),
                ('total_volume', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='总成交量')),
                ('bb_upper', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='BB上轨')),
                ('bb_lower', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='BB下轨')),
                ('kc_upper', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='KC上轨')),
                ('kc_lower', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='KC下轨')),
                ('raw_result', models.JSONField(blank=True, help_text='完整的计算结果JSON', null=True, verbose_name='原始结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'VP-Squeeze分析结果',
                'verbose_name_plural': 'VP-Squeeze分析结果',
                'db_table': 'vp_squeeze_results',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['symbol', 'interval', '-analyzed_at'], name='vp_squeeze__symbol_144396_idx'), models.Index(fields=['squeeze_active', '-analyzed_at'], name='vp_squeeze__squeeze_244e71_idx')],
            },
        ),
    ]
