# Generated by Django 4.2.8 on 2025-11-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='软删除标记，True 表示已删除', verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='记录被软删除的时间', null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(db_index=True, help_text='标签名称，唯一', max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, default='', help_text='标签的详细描述', verbose_name='标签描述')),
                ('color', models.CharField(blank=True, default='#007bff', help_text='标签显示颜色，十六进制格式 (如 #007bff)', max_length=7, verbose_name='标签颜色')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'twitter_tag',
                'ordering': ['name'],
            },
        ),
    ]
