# Generated by Django 4.2.8 on 2025-11-13 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='软删除标记，True 表示已删除', verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='记录被软删除的时间', null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('list_id', models.CharField(db_index=True, help_text='Twitter List 的唯一标识符', max_length=50, unique=True, verbose_name='Twitter List ID')),
                ('name', models.CharField(help_text='Twitter List 的显示名称', max_length=255, verbose_name='List 名称')),
                ('description', models.TextField(blank=True, default='', help_text='Twitter List 的详细描述', verbose_name='List 描述')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃'), ('archived', '已归档')], db_index=True, default='active', help_text='List 的当前状态', max_length=20, verbose_name='状态')),
                ('tags', models.ManyToManyField(blank=True, help_text='关联的分类标签', related_name='twitter_lists', to='twitter.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': 'Twitter List',
                'verbose_name_plural': 'Twitter Lists',
                'db_table': 'twitter_lists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='软删除标记，True 表示已删除', verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='记录被软删除的时间', null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tweet_id', models.CharField(help_text='Twitter 推文的唯一标识符', max_length=50, primary_key=True, serialize=False, verbose_name='推文 ID')),
                ('user_id', models.CharField(db_index=True, default='', help_text='推文作者的 Twitter 用户 ID', max_length=50, verbose_name='用户 ID')),
                ('screen_name', models.CharField(db_index=True, default='unknown', help_text='推文作者的 Twitter 用户名 (@xxx)', max_length=100, verbose_name='用户名')),
                ('user_name', models.CharField(blank=True, default='', help_text='推文作者的显示名称', max_length=200, verbose_name='显示名称')),
                ('content', models.TextField(help_text='推文的完整文本内容', verbose_name='推文内容')),
                ('tweet_created_at', models.DateTimeField(db_index=True, help_text='推文在 Twitter 上的发布时间', verbose_name='推文发布时间')),
                ('retweet_count', models.IntegerField(default=0, help_text='推文的转发次数', verbose_name='转发数')),
                ('favorite_count', models.IntegerField(default=0, help_text='推文的点赞次数', verbose_name='点赞数')),
                ('reply_count', models.IntegerField(default=0, help_text='推文的回复次数', verbose_name='回复数')),
                ('twitter_list', models.ForeignKey(help_text='推文所属的 Twitter List', on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitter.twitterlist', verbose_name='Twitter List')),
            ],
            options={
                'verbose_name': '推文',
                'verbose_name_plural': '推文',
                'db_table': 'twitter_tweets',
                'ordering': ['-tweet_created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='twitterlist',
            index=models.Index(fields=['list_id'], name='twitter_list_id_idx'),
        ),
        migrations.AddIndex(
            model_name='twitterlist',
            index=models.Index(fields=['status'], name='twitter_list_status_idx'),
        ),
        migrations.AddIndex(
            model_name='twitterlist',
            index=models.Index(fields=['created_at'], name='twitter_list_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['twitter_list', 'tweet_created_at'], name='twitter_tweet_list_time_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['user_id'], name='twitter_tweet_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['screen_name'], name='twitter_tweet_screen_name_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['tweet_created_at'], name='twitter_tweet_created_at_idx'),
        ),
    ]
