# Generated by Django 4.2.8 on 2025-11-13 12:46

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_twitterlist_tweet_twitterlist_twitter_list_id_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAnalysisResult',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='软删除标记，True 表示已删除', verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='记录被软删除的时间', null=True, verbose_name='删除时间')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='任务的唯一标识符（UUID）', primary_key=True, serialize=False, verbose_name='任务 ID')),
                ('start_time', models.DateTimeField(help_text='分析的推文时间范围起点', verbose_name='分析起始时间')),
                ('end_time', models.DateTimeField(help_text='分析的推文时间范围终点', verbose_name='分析结束时间')),
                ('prompt_template', models.TextField(help_text='使用的 AI 分析 prompt 内容', verbose_name='Prompt 模板')),
                ('tweet_count', models.IntegerField(default=0, help_text='本次分析的推文总数', verbose_name='推文数量')),
                ('analysis_result', models.JSONField(blank=True, help_text='AI 生成的结构化分析结果（JSON 格式）', null=True, verbose_name='分析结果')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', help_text='任务当前的执行状态', max_length=20, verbose_name='任务状态')),
                ('error_message', models.TextField(blank=True, default='', help_text='任务失败时的错误详情', verbose_name='错误信息')),
                ('cost_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='本次分析的实际 API 调用成本', max_digits=10, verbose_name='实际成本（美元）')),
                ('processing_time', models.FloatField(default=0.0, help_text='任务实际执行时长', verbose_name='处理时长（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='任务创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='任务最后更新时间', verbose_name='更新时间')),
                ('twitter_list', models.ForeignKey(help_text='分析的 Twitter List', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='twitter.twitterlist', verbose_name='Twitter List')),
            ],
            options={
                'verbose_name': 'Twitter 分析结果',
                'verbose_name_plural': 'Twitter 分析结果',
                'db_table': 'twitter_analysis_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['twitter_list', 'created_at'], name='tw_analysis_list_time_idx'), models.Index(fields=['status', 'created_at'], name='tw_analysis_status_time_idx'), models.Index(fields=['created_at'], name='tw_analysis_created_idx')],
            },
        ),
    ]
