# Generated by Django 4.2.8 on 2025-11-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_twitteranalysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Prompt 模板的名称', max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, default='', help_text='模板的详细描述和用途说明', verbose_name='模板描述')),
                ('analysis_type', models.CharField(choices=[('general', '通用分析'), ('opportunity', '项目机会分析'), ('sentiment', '市场情绪分析'), ('news', '新闻事件分析'), ('trading', '交易信号分析'), ('custom', '自定义分析')], default='general', help_text='模板的分析类型分类', max_length=20, verbose_name='分析类型')),
                ('template_content', models.TextField(help_text='包含 {tweet_content} 占位符的完整 prompt 模板', verbose_name='Prompt 模板内容')),
                ('max_tweets_per_batch', models.IntegerField(default=100, help_text='使用此模板时的批次大小限制', verbose_name='每批最大推文数')),
                ('max_cost_per_analysis', models.DecimalField(decimal_places=4, default=10.0, help_text='使用此模板时的成本上限', max_digits=10, verbose_name='每次分析最大成本（美元）')),
                ('is_default', models.BooleanField(default=False, help_text='当没有匹配到特定模板时使用（每种类型只能有一个默认模板）', verbose_name='是否默认模板')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃')], default='active', help_text='模板的启用状态', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('twitter_lists', models.ManyToManyField(blank=True, help_text='应用此模板的 Twitter List（可选，留空表示通用模板）', related_name='prompt_templates', to='twitter.twitterlist', verbose_name='关联的 Twitter Lists')),
            ],
            options={
                'verbose_name': 'Prompt 模板',
                'verbose_name_plural': 'Prompt 模板',
                'db_table': 'twitter_prompt_templates',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['analysis_type', 'status'], name='prompt_type_status_idx'), models.Index(fields=['is_default'], name='prompt_default_idx'), models.Index(fields=['created_at'], name='prompt_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('analysis_type', 'is_default'), name='unique_default_per_type'),
        ),
    ]
