# Generated by Django 4.2.8 on 2025-11-28 11:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='交易对')),
                ('config_name', models.CharField(help_text='如: btc_default_v1', max_length=50, verbose_name='配置名称')),
                ('atr_multiplier', models.DecimalField(decimal_places=2, default=Decimal('0.80'), help_text='网格步长 = ATR * 此倍数', max_digits=5, verbose_name='ATR倍数')),
                ('grid_levels', models.IntegerField(default=10, help_text='上下各N层', verbose_name='网格层数')),
                ('order_size_usdt', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, verbose_name='每格金额(USDT)')),
                ('stop_loss_pct', models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='默认10%', max_digits=5, verbose_name='止损百分比')),
                ('max_position_usdt', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10, verbose_name='最大仓位(USDT)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '策略配置',
                'verbose_name_plural': '策略配置列表',
                'db_table': 'strategy_config',
                'ordering': ['-created_at'],
                'unique_together': {('symbol', 'config_name')},
            },
        ),
        migrations.CreateModel(
            name='GridZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='交易对')),
                ('zone_type', models.CharField(choices=[('support', '支撑区'), ('resistance', '压力区')], db_index=True, max_length=20, verbose_name='区间类型')),
                ('price_low', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='区间下界')),
                ('price_high', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='区间上界')),
                ('confidence', models.IntegerField(default=0, help_text='0-100, 越高越可靠', verbose_name='置信度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(help_text='Scanner每次更新会刷新', verbose_name='过期时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '网格区间',
                'verbose_name_plural': '网格区间列表',
                'db_table': 'grid_zone',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'is_active', 'zone_type'], name='grid_zone_symbol_1ec2da_idx'), models.Index(fields=['expires_at'], name='grid_zone_expires_32aea0_idx')],
            },
        ),
        migrations.CreateModel(
            name='GridStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='交易对')),
                ('strategy_type', models.CharField(choices=[('long', '做多网格'), ('short', '做空网格')], max_length=10, verbose_name='策略类型')),
                ('grid_step_pct', models.DecimalField(decimal_places=4, help_text='如0.0080表示0.8%', max_digits=5, verbose_name='网格步长(%)')),
                ('grid_levels', models.IntegerField(default=10, verbose_name='网格层数')),
                ('order_size', models.DecimalField(decimal_places=8, help_text='币种数量,如0.01 BTC', max_digits=20, verbose_name='每格数量')),
                ('stop_loss_pct', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5, verbose_name='止损百分比')),
                ('status', models.CharField(choices=[('idle', '空闲'), ('active', '运行中'), ('stopped', '已停止'), ('error', '异常')], db_index=True, default='idle', max_length=20, verbose_name='状态')),
                ('entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='入场价格')),
                ('current_pnl', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='当前盈亏(USDT)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='停止时间')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid_trading.strategyconfig', verbose_name='使用的配置')),
            ],
            options={
                'verbose_name': '网格策略',
                'verbose_name_plural': '网格策略列表',
                'db_table': 'grid_strategy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GridOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('buy', '买单'), ('sell', '卖单')], db_index=True, max_length=10, verbose_name='订单类型')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='价格')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='数量')),
                ('status', models.CharField(choices=[('pending', '待成交'), ('filled', '已成交'), ('cancelled', '已撤销')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('filled_at', models.DateTimeField(blank=True, null=True, verbose_name='成交时间')),
                ('simulated_price', models.DecimalField(blank=True, decimal_places=8, help_text='模拟滑点后的价格', max_digits=20, null=True, verbose_name='实际成交价')),
                ('simulated_fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='手续费(USDT)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid_trading.gridstrategy', verbose_name='所属策略')),
            ],
            options={
                'verbose_name': '网格订单',
                'verbose_name_plural': '网格订单列表',
                'db_table': 'grid_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gridstrategy',
            index=models.Index(fields=['symbol', 'status'], name='grid_strate_symbol_e8a925_idx'),
        ),
        migrations.AddIndex(
            model_name='gridstrategy',
            index=models.Index(fields=['created_at'], name='grid_strate_created_89741a_idx'),
        ),
        migrations.AddIndex(
            model_name='gridorder',
            index=models.Index(fields=['strategy', 'status'], name='grid_order_strateg_f05704_idx'),
        ),
        migrations.AddIndex(
            model_name='gridorder',
            index=models.Index(fields=['order_type', 'status'], name='grid_order_order_t_c9bdb0_idx'),
        ),
        migrations.AddIndex(
            model_name='gridorder',
            index=models.Index(fields=['created_at'], name='grid_order_created_150a4d_idx'),
        ),
    ]
