# Generated by Django 4.2.8 on 2025-12-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='交易对')),
                ('interval', models.CharField(db_index=True, help_text='1m, 5m, 15m, 1h, 4h, 1d等', max_length=10, verbose_name='时间周期')),
                ('open_time', models.DateTimeField(db_index=True, verbose_name='开盘时间')),
                ('close_time', models.DateTimeField(verbose_name='收盘时间')),
                ('open', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='开盘价')),
                ('high', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='最低价')),
                ('close', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='收盘价')),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='成交量(base)')),
                ('quote_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, verbose_name='成交额(quote)')),
                ('taker_buy_base_volume', models.DecimalField(blank=True, decimal_places=8, help_text='用于CVD计算', max_digits=30, null=True, verbose_name='主动买入成交量(base)')),
                ('taker_buy_quote_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, verbose_name='主动买入成交额(quote)')),
                ('number_of_trades', models.IntegerField(blank=True, null=True, verbose_name='成交笔数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'K线数据',
                'verbose_name_plural': 'K线数据缓存',
                'db_table': 'kline_data',
                'ordering': ['symbol', 'interval', 'open_time'],
                'indexes': [models.Index(fields=['symbol', 'interval', 'open_time'], name='kline_data_symbol_0811ba_idx'), models.Index(fields=['symbol', 'interval', '-open_time'], name='kline_data_symbol_fc1655_idx'), models.Index(fields=['symbol', 'interval', 'open_time', 'close_time'], name='kline_data_symbol_faa5f7_idx')],
                'unique_together': {('symbol', 'interval', 'open_time')},
            },
        ),
    ]
