# Generated by Django 4.2.8 on 2025-12-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_trading', '0002_add_kline_data_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='交易对')),
                ('base_asset', models.CharField(max_length=10, verbose_name='基础货币')),
                ('quote_asset', models.CharField(max_length=10, verbose_name='计价货币')),
                ('contract_type', models.CharField(default='PERPETUAL', max_length=20, verbose_name='合约类型')),
                ('current_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='当前价格')),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, verbose_name='24小时成交量(USDT)')),
                ('open_interest', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, verbose_name='持仓量(USDT)')),
                ('funding_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='资金费率')),
                ('next_funding_time', models.DateTimeField(blank=True, null=True, verbose_name='下次资金费率时间')),
                ('listing_date', models.DateTimeField(blank=True, null=True, verbose_name='上市时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否活跃')),
                ('market_cap_rank', models.IntegerField(blank=True, null=True, verbose_name='市值排名')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '合约信息',
                'verbose_name_plural': '合约信息缓存',
                'db_table': 'symbol_info',
                'ordering': ['-volume_24h'],
                'indexes': [models.Index(fields=['is_active', 'volume_24h'], name='symbol_info_is_acti_054647_idx'), models.Index(fields=['is_active', 'listing_date'], name='symbol_info_is_acti_e67c53_idx')],
            },
        ),
    ]
