# Generated by Django 4.2.8 on 2025-12-03 07:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grid_trading', '0003_add_symbol_info_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='筛选时间')),
                ('min_volume', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='最小流动性')),
                ('min_days', models.IntegerField(verbose_name='最小上市天数')),
                ('vdr_weight', models.DecimalField(decimal_places=4, default=Decimal('0.40'), max_digits=5, verbose_name='VDR权重')),
                ('ker_weight', models.DecimalField(decimal_places=4, default=Decimal('0.30'), max_digits=5, verbose_name='KER权重')),
                ('ovr_weight', models.DecimalField(decimal_places=4, default=Decimal('0.20'), max_digits=5, verbose_name='OVR权重')),
                ('cvd_weight', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5, verbose_name='CVD权重')),
                ('total_candidates', models.IntegerField(verbose_name='候选标的数')),
                ('execution_time', models.FloatField(verbose_name='执行耗时(秒)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '筛选记录',
                'verbose_name_plural': '筛选记录列表',
                'db_table': 'screening_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(db_index=True, verbose_name='排名')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='标的代码')),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='当前价格')),
                ('vdr', models.FloatField(verbose_name='VDR(波动率-位移比)')),
                ('ker', models.FloatField(verbose_name='KER(考夫曼效率比)')),
                ('ovr', models.FloatField(verbose_name='OVR(持仓/成交比)')),
                ('cvd_divergence', models.BooleanField(default=False, verbose_name='CVD背离')),
                ('vdr_score', models.FloatField(verbose_name='VDR得分')),
                ('ker_score', models.FloatField(verbose_name='KER得分')),
                ('ovr_score', models.FloatField(verbose_name='OVR得分')),
                ('cvd_score', models.FloatField(verbose_name='CVD得分')),
                ('composite_index', models.FloatField(db_index=True, verbose_name='综合指数')),
                ('grid_upper_limit', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='网格上限')),
                ('grid_lower_limit', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='网格下限')),
                ('grid_count', models.IntegerField(verbose_name='推荐网格数')),
                ('grid_step', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='网格步长')),
                ('take_profit_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='止盈价格')),
                ('stop_loss_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='止损价格')),
                ('take_profit_pct', models.FloatField(verbose_name='止盈百分比(%)')),
                ('stop_loss_pct', models.FloatField(verbose_name='止损百分比(%)')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='grid_trading.screeningrecord', verbose_name='所属筛选记录')),
            ],
            options={
                'verbose_name': '筛选结果',
                'verbose_name_plural': '筛选结果列表',
                'db_table': 'screening_result_record',
                'ordering': ['record', 'rank'],
            },
        ),
        migrations.AddIndex(
            model_name='screeningrecord',
            index=models.Index(fields=['-created_at'], name='screening_r_created_cf2c15_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningresultmodel',
            index=models.Index(fields=['record', 'rank'], name='screening_r_record__b74d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningresultmodel',
            index=models.Index(fields=['symbol'], name='screening_r_symbol_a69526_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningresultmodel',
            index=models.Index(fields=['-composite_index'], name='screening_r_composi_9d9a9e_idx'),
        ),
    ]
