# Generated by Django 4.2.8 on 2025-12-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_trading', '0004_add_screening_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresultmodel',
            name='amplitude_sum_15m',
            field=models.FloatField(default=0.0, verbose_name='15分钟振幅累计'),
        ),
    ]
