# Generated by Django 4.2.8 on 2025-12-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_trading', '0005_add_amplitude_sum_15m'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresultmodel',
            name='annual_funding_rate',
            field=models.FloatField(default=0.0, help_text='基于过去24小时平均资金费率年化，正值表示做空有利', verbose_name='年化资金费率(%)'),
        ),
        migrations.AlterField(
            model_name='screeningresultmodel',
            name='amplitude_sum_15m',
            field=models.FloatField(default=0.0, help_text='最近100根15分钟K线的振幅百分比累加', verbose_name='15分钟振幅累计(%)'),
        ),
    ]
