# Generated by Django 4.2.8 on 2025-12-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_trading', '0006_screeningresultmodel_annual_funding_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningrecord',
            name='filter_min_amplitude',
            field=models.FloatField(blank=True, help_text='15m振幅>=此值才会被筛选出来', null=True, verbose_name='15m振幅最小值过滤(%)'),
        ),
        migrations.AddField(
            model_name='screeningrecord',
            name='filter_min_funding_rate',
            field=models.FloatField(blank=True, help_text='年化资金费率>=此值才会被筛选出来', null=True, verbose_name='年化资金费率最小值过滤(%)'),
        ),
        migrations.AddField(
            model_name='screeningrecord',
            name='filter_min_ker',
            field=models.FloatField(blank=True, help_text='KER>=此值才会被筛选出来', null=True, verbose_name='KER最小值过滤'),
        ),
        migrations.AddField(
            model_name='screeningrecord',
            name='filter_min_vdr',
            field=models.FloatField(blank=True, help_text='VDR>=此值才会被筛选出来', null=True, verbose_name='VDR最小值过滤'),
        ),
    ]
