# Generated by Django 4.2.8 on 2025-12-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_trading', '0007_add_filter_conditions_to_screening_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresultmodel',
            name='fdv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fully Diluted Valuation', max_digits=30, null=True, verbose_name='完全稀释市值(USD)'),
        ),
        migrations.AddField(
            model_name='screeningresultmodel',
            name='oi_fdv_ratio',
            field=models.FloatField(blank=True, help_text='持仓量占完全稀释市值的百分比', null=True, verbose_name='OI/FDV比率(%)'),
        ),
        migrations.AddField(
            model_name='screeningresultmodel',
            name='open_interest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='合约未平仓总量(美元价值)', max_digits=30, null=True, verbose_name='持仓量(USDT)'),
        ),
    ]
