# Generated by Django 4.2.8 on 2025-12-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_trading', '0008_screeningresultmodel_fdv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresultmodel',
            name='has_spot',
            field=models.BooleanField(default=False, help_text='该合约是否在币安现货市场有对应交易对', verbose_name='是否有现货'),
        ),
        migrations.AddField(
            model_name='symbolinfo',
            name='has_spot',
            field=models.BooleanField(default=False, help_text='该合约是否在币安现货市场有对应交易对', verbose_name='是否有现货'),
        ),
    ]
