# Generated by Django 4.2.8 on 2025-12-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_trading', '0010_add_volume_24h_calculated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningresultmodel',
            name='volume_24h_calculated',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='从1440根1m K线计算的24小时交易量', max_digits=30, null=True, verbose_name='24h交易量(USDT)'),
        ),
    ]
