# Generated by Django 4.2.8 on 2025-12-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_trading', '0011_alter_screeningresultmodel_volume_24h_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresultmodel',
            name='vol_oi_ratio',
            field=models.FloatField(default=0.0, help_text='24h交易量/持仓量比率', verbose_name='Vol/OI比率'),
        ),
    ]
