# Generated by Django 4.2.8 on 2025-12-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_trading', '0012_screeningresultmodel_vol_oi_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresultmodel',
            name='ma20_slope',
            field=models.FloatField(default=0.0, help_text='MA(20)均线斜率(标准化), 正值=上升趋势, 负值=下降趋势', verbose_name='MA20斜率'),
        ),
        migrations.AddField(
            model_name='screeningresultmodel',
            name='ma99_slope',
            field=models.FloatField(default=0.0, help_text='MA(99)均线斜率(标准化), 正值=上升趋势, 负值=下降趋势', verbose_name='MA99斜率'),
        ),
    ]
