# Generated by Django 4.2.8 on 2025-12-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_trading', '0014_add_entry_recommendation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresultmodel',
            name='entry_candidates_json',
            field=models.JSONField(blank=True, default=list, help_text='存储3个挂单候选方案的详细信息', verbose_name='3档挂单候选'),
        ),
        migrations.AlterField(
            model_name='screeningresultmodel',
            name='ma20_slope',
            field=models.FloatField(default=0.0, help_text='EMA(20)均线斜率(标准化), 正值=上升趋势, 负值=下降趋势', verbose_name='EMA20斜率'),
        ),
        migrations.AlterField(
            model_name='screeningresultmodel',
            name='ma99_slope',
            field=models.FloatField(default=0.0, help_text='EMA(99)均线斜率(标准化), 正值=上升趋势, 负值=下降趋势', verbose_name='EMA99斜率'),
        ),
        migrations.AlterField(
            model_name='screeningresultmodel',
            name='recommended_entry_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='推荐挂单价'),
        ),
    ]
