# Generated by Django 4.2.8 on 2025-12-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_trading', '0015_add_entry_candidates_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresultmodel',
            name='drawdown_from_high_pct',
            field=models.FloatField(default=0.0, help_text='当前价格相对300根4h高点的回落比例，正值=已回落，负值=创新高', verbose_name='高点回落(%)'),
        ),
        migrations.AddField(
            model_name='screeningresultmodel',
            name='highest_price_300',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='300根4h K线内的最高价', max_digits=20, null=True, verbose_name='300根4h高点'),
        ),
    ]
