# Generated by Django 4.2.8 on 2025-12-05 07:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grid_trading', '0016_add_drawdown_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='唯一标识，如 btc_short_grid', max_length=100, unique=True, verbose_name='配置名称')),
                ('exchange', models.CharField(help_text='交易所代码: binance/okx/bybit', max_length=50, verbose_name='交易所')),
                ('symbol', models.CharField(help_text='交易对代码: BTCUSDT', max_length=20, verbose_name='交易对')),
                ('grid_mode', models.CharField(choices=[('SHORT', '做空网格'), ('NEUTRAL', '中性网格'), ('LONG', '做多网格')], help_text='做空/中性/做多', max_length=10, verbose_name='网格模式')),
                ('upper_price', models.DecimalField(decimal_places=8, help_text='网格价格上界', max_digits=20, verbose_name='价格上界')),
                ('lower_price', models.DecimalField(decimal_places=8, help_text='网格价格下界', max_digits=20, verbose_name='价格下界')),
                ('grid_levels', models.IntegerField(help_text='网格总数量，至少5层', verbose_name='网格层数')),
                ('trade_amount', models.DecimalField(decimal_places=8, help_text='每次开仓的数量', max_digits=20, verbose_name='单笔开仓数量')),
                ('max_position_size', models.DecimalField(decimal_places=8, help_text='最大持仓数量', max_digits=20, verbose_name='最大持仓限制')),
                ('stop_loss_buffer_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0050'), help_text='默认0.5%', max_digits=6, verbose_name='止损缓冲区百分比')),
                ('refresh_interval_ms', models.IntegerField(default=1000, help_text='订单同步间隔，默认1000ms', verbose_name='轮询间隔(毫秒)')),
                ('price_tick', models.DecimalField(decimal_places=8, help_text='如0.01', max_digits=20, verbose_name='价格精度')),
                ('qty_step', models.DecimalField(decimal_places=8, help_text='如0.001', max_digits=20, verbose_name='数量精度')),
                ('is_active', models.BooleanField(default=False, help_text='启用后策略开始运行', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网格配置',
                'verbose_name_plural': '网格配置',
                'db_table': 'grid_config',
            },
        ),
        migrations.CreateModel(
            name='GridLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_index', models.IntegerField(help_text='层级索引，0为中心，负数为下方，正数为上方', verbose_name='层级索引')),
                ('price', models.DecimalField(decimal_places=8, help_text='该层级的价格', max_digits=20, verbose_name='网格价位')),
                ('side', models.CharField(choices=[('BUY', '买入'), ('SELL', '卖出')], help_text='买入或卖出', max_length=10, verbose_name='方向')),
                ('status', models.CharField(choices=[('idle', '空闲'), ('entry_working', '开仓单已挂单'), ('position_open', '持仓中'), ('exit_working', '平仓单已挂单')], default='idle', help_text='层级当前状态', max_length=20, verbose_name='状态')),
                ('entry_order_id', models.CharField(blank=True, help_text='交易所开仓订单ID', max_length=50, null=True, verbose_name='开仓订单ID')),
                ('exit_order_id', models.CharField(blank=True, help_text='交易所平仓订单ID', max_length=50, null=True, verbose_name='平仓订单ID')),
                ('entry_client_id', models.CharField(blank=True, help_text='客户端开仓订单ID', max_length=100, null=True, verbose_name='开仓客户端ID')),
                ('exit_client_id', models.CharField(blank=True, help_text='客户端平仓订单ID', max_length=100, null=True, verbose_name='平仓客户端ID')),
                ('blocked_until', models.BigIntegerField(blank=True, help_text='Unix毫秒时间戳，为NULL表示不冷却', null=True, verbose_name='冷却时间戳')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='grid_trading.gridconfig', verbose_name='网格配置')),
            ],
            options={
                'verbose_name': '网格层级',
                'verbose_name_plural': '网格层级',
                'db_table': 'grid_level',
            },
        ),
        migrations.CreateModel(
            name='GridStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(help_text='统计周期的开始时间', verbose_name='统计周期起始')),
                ('period_end', models.DateTimeField(help_text='统计周期的结束时间', verbose_name='统计周期结束')),
                ('total_trades', models.IntegerField(default=0, help_text='该周期内所有订单的数量', verbose_name='总交易次数')),
                ('filled_entry_orders', models.IntegerField(default=0, help_text='开仓订单成交数量', verbose_name='成交开仓单数')),
                ('filled_exit_orders', models.IntegerField(default=0, help_text='平仓订单成交数量', verbose_name='成交平仓单数')),
                ('canceled_orders', models.IntegerField(default=0, help_text='撤销订单的数量', verbose_name='撤单数')),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0, help_text='已平仓的盈亏', max_digits=20, verbose_name='已实现盈亏')),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, default=0, help_text='当前持仓的浮动盈亏', max_digits=20, verbose_name='未实现盈亏')),
                ('total_pnl', models.DecimalField(decimal_places=8, default=0, help_text='已实现 + 未实现盈亏', max_digits=20, verbose_name='总盈亏')),
                ('max_position_size', models.DecimalField(decimal_places=8, default=0, help_text='该周期内的最大持仓数量', max_digits=20, verbose_name='最大持仓')),
                ('avg_position_size', models.DecimalField(decimal_places=8, default=0, help_text='该周期内的平均持仓数量', max_digits=20, verbose_name='平均持仓')),
                ('current_position_size', models.DecimalField(decimal_places=8, default=0, help_text='统计时刻的持仓数量', max_digits=20, verbose_name='当前持仓')),
                ('stop_loss_triggered_count', models.IntegerField(default=0, help_text='止损被触发的次数', verbose_name='止损触发次数')),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=0, help_text='最大回撤百分比', max_digits=10, verbose_name='最大回撤')),
                ('skipped_orders_count', models.IntegerField(default=0, help_text='因持仓限制等原因跳过的订单数', verbose_name='跳过订单数')),
                ('avg_fill_time_seconds', models.DecimalField(decimal_places=2, default=0, help_text='订单从挂单到成交的平均时间', max_digits=10, verbose_name='平均成交时间(秒)')),
                ('grid_utilization_pct', models.DecimalField(decimal_places=2, default=0, help_text='被触及的网格层级占总层级的百分比', max_digits=6, verbose_name='网格利用率(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='grid_trading.gridconfig', verbose_name='网格配置')),
            ],
            options={
                'verbose_name': '网格统计',
                'verbose_name_plural': '网格统计',
                'db_table': 'grid_statistics',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='OrderIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, help_text='创建订单后由交易所返回', max_length=50, null=True, verbose_name='交易所订单ID')),
                ('client_order_id', models.CharField(help_text='业务唯一标识，用于幂等性保证', max_length=100, unique=True, verbose_name='客户端订单ID')),
                ('level_index', models.IntegerField(help_text='对应的网格层级索引', verbose_name='网格层级')),
                ('intent', models.CharField(choices=[('ENTRY', '开仓'), ('EXIT', '平仓')], help_text='开仓或平仓', max_length=10, verbose_name='意图')),
                ('side', models.CharField(choices=[('BUY', '买入'), ('SELL', '卖出')], help_text='买入或卖出', max_length=10, verbose_name='方向')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='订单价格')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='订单数量')),
                ('status', models.CharField(choices=[('NEW', '新建'), ('PARTIALLY_FILLED', '部分成交'), ('FILLED', '完全成交'), ('CANCELED', '已撤销'), ('REJECTED', '已拒绝'), ('EXPIRED', '已过期')], default='NEW', max_length=20, verbose_name='订单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='订单成交或撤销的时间', null=True, verbose_name='完结时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_intents', to='grid_trading.gridconfig', verbose_name='网格配置')),
            ],
            options={
                'verbose_name': '订单意图',
                'verbose_name_plural': '订单意图',
                'db_table': 'order_intent',
            },
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('INIT', '初始化'), ('ORDER_CREATE', '创建订单'), ('ORDER_FILL', '订单成交'), ('ORDER_CANCEL', '订单撤销'), ('STOP_LOSS', '止损触发'), ('ERROR', '错误'), ('WARNING', '警告'), ('INFO', '信息')], max_length=20, verbose_name='日志类型')),
                ('detail', models.TextField(help_text='日志的详细内容', verbose_name='详细描述')),
                ('timestamp', models.BigIntegerField(help_text='事件发生的时间戳', verbose_name='Unix毫秒时间戳')),
                ('order_id', models.CharField(blank=True, help_text='如果是订单相关事件，记录订单ID', max_length=50, null=True, verbose_name='关联订单ID')),
                ('level_index', models.IntegerField(blank=True, help_text='如果是层级相关事件，记录层级索引', null=True, verbose_name='网格层级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_logs', to='grid_trading.gridconfig', verbose_name='网格配置')),
            ],
            options={
                'verbose_name': '交易日志',
                'verbose_name_plural': '交易日志',
                'db_table': 'trade_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='gridorder',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='gridstrategy',
            name='config',
        ),
        migrations.DeleteModel(
            name='GridZone',
        ),
        migrations.DeleteModel(
            name='KlineData',
        ),
        migrations.RemoveField(
            model_name='screeningresultmodel',
            name='record',
        ),
        migrations.AlterUniqueTogether(
            name='strategyconfig',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='SymbolInfo',
        ),
        migrations.DeleteModel(
            name='GridOrder',
        ),
        migrations.DeleteModel(
            name='GridStrategy',
        ),
        migrations.DeleteModel(
            name='ScreeningRecord',
        ),
        migrations.DeleteModel(
            name='ScreeningResultModel',
        ),
        migrations.DeleteModel(
            name='StrategyConfig',
        ),
        migrations.AddIndex(
            model_name='gridconfig',
            index=models.Index(fields=['name'], name='idx_config_name'),
        ),
        migrations.AddIndex(
            model_name='gridconfig',
            index=models.Index(fields=['exchange', 'symbol'], name='idx_config_exchange_symbol'),
        ),
        migrations.AddIndex(
            model_name='gridconfig',
            index=models.Index(fields=['is_active'], name='idx_config_active'),
        ),
        migrations.AddIndex(
            model_name='tradelog',
            index=models.Index(fields=['config', '-timestamp'], name='idx_log_config_time'),
        ),
        migrations.AddIndex(
            model_name='tradelog',
            index=models.Index(fields=['config', 'log_type'], name='idx_log_config_type'),
        ),
        migrations.AddIndex(
            model_name='tradelog',
            index=models.Index(fields=['order_id'], name='idx_log_order_id'),
        ),
        migrations.AddIndex(
            model_name='orderintent',
            index=models.Index(fields=['config', 'level_index'], name='idx_intent_config_level'),
        ),
        migrations.AddIndex(
            model_name='orderintent',
            index=models.Index(fields=['order_id'], name='idx_intent_order_id'),
        ),
        migrations.AddIndex(
            model_name='orderintent',
            index=models.Index(fields=['client_order_id'], name='idx_intent_client_id'),
        ),
        migrations.AddIndex(
            model_name='orderintent',
            index=models.Index(fields=['status'], name='idx_intent_status'),
        ),
        migrations.AddIndex(
            model_name='gridstatistics',
            index=models.Index(fields=['config', '-period_end'], name='idx_stats_config_period'),
        ),
        migrations.AddIndex(
            model_name='gridlevel',
            index=models.Index(fields=['config', 'level_index'], name='idx_level_config_index'),
        ),
        migrations.AddIndex(
            model_name='gridlevel',
            index=models.Index(fields=['config', 'status'], name='idx_level_config_status'),
        ),
        migrations.AlterUniqueTogether(
            name='gridlevel',
            unique_together={('config', 'level_index')},
        ),
    ]
