# Generated by Django 4.2.8 on 2025-12-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grid_trading", "0017_gridconfig_gridlevel_gridstatistics_orderintent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradelog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("info", "信息"),
                    ("warn", "警告"),
                    ("error", "错误"),
                    ("order", "订单"),
                    ("fill", "成交"),
                ],
                max_length=20,
                verbose_name="日志类型",
            ),
        ),
    ]
