# Generated by Django 4.2.8 on 2025-12-05 13:18

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("grid_trading", "0018_alter_tradelog_log_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GridOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("buy", "买单"), ("sell", "卖单")],
                        db_index=True,
                        max_length=10,
                        verbose_name="订单类型",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="价格"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="数量"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待成交"),
                            ("filled", "已成交"),
                            ("cancelled", "已撤销"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("filled_at", models.DateTimeField(blank=True, null=True, verbose_name="成交时间")),
                (
                    "simulated_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="模拟滑点后的价格",
                        max_digits=20,
                        null=True,
                        verbose_name="实际成交价",
                    ),
                ),
                (
                    "simulated_fee",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0.00"),
                        max_digits=20,
                        verbose_name="手续费(USDT)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "网格订单",
                "verbose_name_plural": "网格订单列表",
                "db_table": "grid_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GridStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20, verbose_name="交易对")),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[("long", "做多网格"), ("short", "做空网格")],
                        max_length=10,
                        verbose_name="策略类型",
                    ),
                ),
                (
                    "grid_step_pct",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="如0.0080表示0.8%",
                        max_digits=5,
                        verbose_name="网格步长(%)",
                    ),
                ),
                ("grid_levels", models.IntegerField(default=10, verbose_name="网格层数")),
                (
                    "order_size",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="币种数量,如0.01 BTC",
                        max_digits=20,
                        verbose_name="每格数量",
                    ),
                ),
                (
                    "stop_loss_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.10"),
                        max_digits=5,
                        verbose_name="止损百分比",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "空闲"),
                            ("active", "运行中"),
                            ("stopped", "已停止"),
                            ("error", "异常"),
                        ],
                        db_index=True,
                        default="idle",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="入场价格",
                    ),
                ),
                (
                    "current_pnl",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0.00"),
                        max_digits=20,
                        verbose_name="当前盈亏(USDT)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="启动时间"),
                ),
                (
                    "stopped_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="停止时间"),
                ),
            ],
            options={
                "verbose_name": "网格策略",
                "verbose_name_plural": "网格策略列表",
                "db_table": "grid_strategy",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GridZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20, verbose_name="交易对")),
                (
                    "zone_type",
                    models.CharField(
                        choices=[("support", "支撑区"), ("resistance", "压力区")],
                        db_index=True,
                        max_length=20,
                        verbose_name="区间类型",
                    ),
                ),
                (
                    "price_low",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="区间下界"),
                ),
                (
                    "price_high",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="区间上界"),
                ),
                (
                    "confidence",
                    models.IntegerField(
                        default=0, help_text="0-100, 越高越可靠", verbose_name="置信度"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Scanner每次更新会刷新", verbose_name="过期时间"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="是否激活"),
                ),
            ],
            options={
                "verbose_name": "网格区间",
                "verbose_name_plural": "网格区间列表",
                "db_table": "grid_zone",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KlineData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20, verbose_name="交易对")),
                (
                    "interval",
                    models.CharField(
                        db_index=True,
                        help_text="1m, 5m, 15m, 1h, 4h, 1d等",
                        max_length=10,
                        verbose_name="时间周期",
                    ),
                ),
                ("open_time", models.DateTimeField(db_index=True, verbose_name="开盘时间")),
                ("close_time", models.DateTimeField(verbose_name="收盘时间")),
                (
                    "open",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="开盘价"),
                ),
                (
                    "high",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="最高价"),
                ),
                (
                    "low",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="最低价"),
                ),
                (
                    "close",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="收盘价"),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=8, max_digits=30, verbose_name="成交量(base)"
                    ),
                ),
                (
                    "quote_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=30,
                        null=True,
                        verbose_name="成交额(quote)",
                    ),
                ),
                (
                    "taker_buy_base_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="用于CVD计算",
                        max_digits=30,
                        null=True,
                        verbose_name="主动买入成交量(base)",
                    ),
                ),
                (
                    "taker_buy_quote_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=30,
                        null=True,
                        verbose_name="主动买入成交额(quote)",
                    ),
                ),
                (
                    "number_of_trades",
                    models.IntegerField(blank=True, null=True, verbose_name="成交笔数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "K线数据",
                "verbose_name_plural": "K线数据缓存",
                "db_table": "kline_data",
                "ordering": ["symbol", "interval", "open_time"],
            },
        ),
        migrations.CreateModel(
            name="ScreeningRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="筛选时间"
                    ),
                ),
                (
                    "min_volume",
                    models.DecimalField(decimal_places=2, max_digits=20, verbose_name="最小流动性"),
                ),
                ("min_days", models.IntegerField(verbose_name="最小上市天数")),
                (
                    "vdr_weight",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.40"),
                        max_digits=5,
                        verbose_name="VDR权重",
                    ),
                ),
                (
                    "ker_weight",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.30"),
                        max_digits=5,
                        verbose_name="KER权重",
                    ),
                ),
                (
                    "ovr_weight",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.20"),
                        max_digits=5,
                        verbose_name="OVR权重",
                    ),
                ),
                (
                    "cvd_weight",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.10"),
                        max_digits=5,
                        verbose_name="CVD权重",
                    ),
                ),
                (
                    "filter_min_vdr",
                    models.FloatField(
                        blank=True,
                        help_text="VDR>=此值才会被筛选出来",
                        null=True,
                        verbose_name="VDR最小值过滤",
                    ),
                ),
                (
                    "filter_min_ker",
                    models.FloatField(
                        blank=True,
                        help_text="KER>=此值才会被筛选出来",
                        null=True,
                        verbose_name="KER最小值过滤",
                    ),
                ),
                (
                    "filter_min_amplitude",
                    models.FloatField(
                        blank=True,
                        help_text="15m振幅>=此值才会被筛选出来",
                        null=True,
                        verbose_name="15m振幅最小值过滤(%)",
                    ),
                ),
                (
                    "filter_min_funding_rate",
                    models.FloatField(
                        blank=True,
                        help_text="年化资金费率>=此值才会被筛选出来",
                        null=True,
                        verbose_name="年化资金费率最小值过滤(%)",
                    ),
                ),
                ("total_candidates", models.IntegerField(verbose_name="候选标的数")),
                ("execution_time", models.FloatField(verbose_name="执行耗时(秒)")),
                ("notes", models.TextField(blank=True, default="", verbose_name="备注")),
            ],
            options={
                "verbose_name": "筛选记录",
                "verbose_name_plural": "筛选记录列表",
                "db_table": "screening_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SymbolInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="交易对"
                    ),
                ),
                ("base_asset", models.CharField(max_length=10, verbose_name="基础货币")),
                ("quote_asset", models.CharField(max_length=10, verbose_name="计价货币")),
                (
                    "contract_type",
                    models.CharField(default="PERPETUAL", max_length=20, verbose_name="合约类型"),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="当前价格",
                    ),
                ),
                (
                    "volume_24h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=30,
                        null=True,
                        verbose_name="24小时成交量(USDT)",
                    ),
                ),
                (
                    "open_interest",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=30,
                        null=True,
                        verbose_name="持仓量(USDT)",
                    ),
                ),
                (
                    "funding_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="资金费率",
                    ),
                ),
                (
                    "next_funding_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="下次资金费率时间"),
                ),
                (
                    "listing_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="上市时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="是否活跃"),
                ),
                (
                    "market_cap_rank",
                    models.IntegerField(blank=True, null=True, verbose_name="市值排名"),
                ),
                (
                    "has_spot",
                    models.BooleanField(
                        default=False,
                        help_text="该合约是否在币安现货市场有对应交易对",
                        verbose_name="是否有现货",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True, verbose_name="最后更新时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "合约信息",
                "verbose_name_plural": "合约信息缓存",
                "db_table": "symbol_info",
                "ordering": ["-volume_24h"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "volume_24h"], name="symbol_info_is_acti_054647_idx"
                    ),
                    models.Index(
                        fields=["is_active", "listing_date"], name="symbol_info_is_acti_e67c53_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StrategyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20, verbose_name="交易对")),
                (
                    "config_name",
                    models.CharField(
                        help_text="如: btc_default_v1", max_length=50, verbose_name="配置名称"
                    ),
                ),
                (
                    "atr_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.80"),
                        help_text="网格步长 = ATR * 此倍数",
                        max_digits=5,
                        verbose_name="ATR倍数",
                    ),
                ),
                (
                    "grid_levels",
                    models.IntegerField(default=10, help_text="上下各N层", verbose_name="网格层数"),
                ),
                (
                    "order_size_usdt",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=10,
                        verbose_name="每格金额(USDT)",
                    ),
                ),
                (
                    "stop_loss_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.10"),
                        help_text="默认10%",
                        max_digits=5,
                        verbose_name="止损百分比",
                    ),
                ),
                (
                    "max_position_usdt",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        max_digits=10,
                        verbose_name="最大仓位(USDT)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="是否激活"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "策略配置",
                "verbose_name_plural": "策略配置列表",
                "db_table": "strategy_config",
                "ordering": ["-created_at"],
                "unique_together": {("symbol", "config_name")},
            },
        ),
        migrations.CreateModel(
            name="ScreeningResultModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rank", models.IntegerField(db_index=True, verbose_name="排名")),
                ("symbol", models.CharField(db_index=True, max_length=20, verbose_name="标的代码")),
                (
                    "current_price",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="当前价格"),
                ),
                ("vdr", models.FloatField(verbose_name="VDR(波动率-位移比)")),
                ("ker", models.FloatField(verbose_name="KER(考夫曼效率比)")),
                ("ovr", models.FloatField(verbose_name="OVR(持仓/成交比)")),
                ("cvd_divergence", models.BooleanField(default=False, verbose_name="CVD背离")),
                (
                    "amplitude_sum_15m",
                    models.FloatField(
                        default=0.0,
                        help_text="最近100根15分钟K线的振幅百分比累加",
                        verbose_name="15分钟振幅累计(%)",
                    ),
                ),
                (
                    "annual_funding_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="基于过去24小时平均资金费率年化，正值表示做空有利",
                        verbose_name="年化资金费率(%)",
                    ),
                ),
                (
                    "open_interest",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="合约未平仓总量(美元价值)",
                        max_digits=30,
                        null=True,
                        verbose_name="持仓量(USDT)",
                    ),
                ),
                (
                    "volume_24h_calculated",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="从1440根1m K线计算的24小时交易量",
                        max_digits=30,
                        null=True,
                        verbose_name="24h交易量(USDT)",
                    ),
                ),
                (
                    "vol_oi_ratio",
                    models.FloatField(
                        default=0.0, help_text="24h交易量/持仓量比率", verbose_name="Vol/OI比率"
                    ),
                ),
                (
                    "fdv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fully Diluted Valuation",
                        max_digits=30,
                        null=True,
                        verbose_name="完全稀释市值(USD)",
                    ),
                ),
                (
                    "oi_fdv_ratio",
                    models.FloatField(
                        blank=True,
                        help_text="持仓量占完全稀释市值的百分比",
                        null=True,
                        verbose_name="OI/FDV比率(%)",
                    ),
                ),
                (
                    "has_spot",
                    models.BooleanField(
                        default=False,
                        help_text="该合约是否在币安现货市场有对应交易对",
                        verbose_name="是否有现货",
                    ),
                ),
                (
                    "ma99_slope",
                    models.FloatField(
                        default=0.0,
                        help_text="EMA(99)均线斜率(标准化), 正值=上升趋势, 负值=下降趋势",
                        verbose_name="EMA99斜率",
                    ),
                ),
                (
                    "ma20_slope",
                    models.FloatField(
                        default=0.0,
                        help_text="EMA(20)均线斜率(标准化), 正值=上升趋势, 负值=下降趋势",
                        verbose_name="EMA20斜率",
                    ),
                ),
                ("vdr_score", models.FloatField(verbose_name="VDR得分")),
                ("ker_score", models.FloatField(verbose_name="KER得分")),
                ("ovr_score", models.FloatField(verbose_name="OVR得分")),
                ("cvd_score", models.FloatField(verbose_name="CVD得分")),
                ("composite_index", models.FloatField(db_index=True, verbose_name="综合指数")),
                (
                    "grid_upper_limit",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="网格上限"),
                ),
                (
                    "grid_lower_limit",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="网格下限"),
                ),
                ("grid_count", models.IntegerField(verbose_name="推荐网格数")),
                (
                    "grid_step",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="网格步长"),
                ),
                (
                    "take_profit_price",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="止盈价格"),
                ),
                (
                    "stop_loss_price",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="止损价格"),
                ),
                ("take_profit_pct", models.FloatField(verbose_name="止盈百分比(%)")),
                ("stop_loss_pct", models.FloatField(verbose_name="止损百分比(%)")),
                (
                    "rsi_15m",
                    models.FloatField(
                        default=50.0, help_text="15分钟RSI指标", verbose_name="RSI(15m)"
                    ),
                ),
                (
                    "recommended_entry_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="推荐挂单价",
                    ),
                ),
                (
                    "entry_trigger_prob_24h",
                    models.FloatField(
                        default=0.0, help_text="24小时内触发概率(0-1)", verbose_name="触发概率(24h)"
                    ),
                ),
                (
                    "entry_trigger_prob_72h",
                    models.FloatField(
                        default=0.0, help_text="72小时内触发概率(0-1)", verbose_name="触发概率(72h)"
                    ),
                ),
                (
                    "entry_strategy_label",
                    models.CharField(
                        default="立即入场",
                        help_text="立即入场/保守反弹/理论反弹",
                        max_length=20,
                        verbose_name="入场策略",
                    ),
                ),
                (
                    "entry_rebound_pct",
                    models.FloatField(
                        default=0.0, help_text="相对当前价的反弹百分比", verbose_name="反弹幅度(%)"
                    ),
                ),
                (
                    "entry_avg_trigger_time",
                    models.FloatField(
                        default=0.0,
                        help_text="历史平均触发时间（小时）",
                        verbose_name="平均触发时间(h)",
                    ),
                ),
                (
                    "entry_expected_return_24h",
                    models.FloatField(
                        default=0.0, help_text="24小时期望收益", verbose_name="期望收益(24h)"
                    ),
                ),
                (
                    "entry_candidates_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="存储3个挂单候选方案的详细信息",
                        verbose_name="3档挂单候选",
                    ),
                ),
                (
                    "highest_price_300",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="300根4h K线内的最高价",
                        max_digits=20,
                        null=True,
                        verbose_name="300根4h高点",
                    ),
                ),
                (
                    "drawdown_from_high_pct",
                    models.FloatField(
                        default=0.0,
                        help_text="当前价格相对300根4h高点的回落比例，正值=已回落，负值=创新高",
                        verbose_name="高点回落(%)",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="grid_trading.screeningrecord",
                        verbose_name="所属筛选记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "筛选结果",
                "verbose_name_plural": "筛选结果列表",
                "db_table": "screening_result_record",
                "ordering": ["record", "rank"],
            },
        ),
        migrations.AddIndex(
            model_name="screeningrecord",
            index=models.Index(fields=["-created_at"], name="screening_r_created_cf2c15_idx"),
        ),
        migrations.AddIndex(
            model_name="klinedata",
            index=models.Index(
                fields=["symbol", "interval", "open_time"], name="kline_data_symbol_0811ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="klinedata",
            index=models.Index(
                fields=["symbol", "interval", "-open_time"], name="kline_data_symbol_fc1655_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="klinedata",
            index=models.Index(
                fields=["symbol", "interval", "open_time", "close_time"],
                name="kline_data_symbol_faa5f7_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="klinedata",
            unique_together={("symbol", "interval", "open_time")},
        ),
        migrations.AddIndex(
            model_name="gridzone",
            index=models.Index(
                fields=["symbol", "is_active", "zone_type"], name="grid_zone_symbol_1ec2da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gridzone",
            index=models.Index(fields=["expires_at"], name="grid_zone_expires_32aea0_idx"),
        ),
        migrations.AddField(
            model_name="gridstrategy",
            name="config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="grid_trading.strategyconfig",
                verbose_name="使用的配置",
            ),
        ),
        migrations.AddField(
            model_name="gridorder",
            name="strategy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="grid_trading.gridstrategy",
                verbose_name="所属策略",
            ),
        ),
        migrations.AddIndex(
            model_name="screeningresultmodel",
            index=models.Index(fields=["record", "rank"], name="screening_r_record__b74d6b_idx"),
        ),
        migrations.AddIndex(
            model_name="screeningresultmodel",
            index=models.Index(fields=["symbol"], name="screening_r_symbol_a69526_idx"),
        ),
        migrations.AddIndex(
            model_name="screeningresultmodel",
            index=models.Index(fields=["-composite_index"], name="screening_r_composi_9d9a9e_idx"),
        ),
        migrations.AddIndex(
            model_name="gridstrategy",
            index=models.Index(fields=["symbol", "status"], name="grid_strate_symbol_e8a925_idx"),
        ),
        migrations.AddIndex(
            model_name="gridstrategy",
            index=models.Index(fields=["created_at"], name="grid_strate_created_89741a_idx"),
        ),
        migrations.AddIndex(
            model_name="gridorder",
            index=models.Index(fields=["strategy", "status"], name="grid_order_strateg_f05704_idx"),
        ),
        migrations.AddIndex(
            model_name="gridorder",
            index=models.Index(
                fields=["order_type", "status"], name="grid_order_order_t_c9bdb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gridorder",
            index=models.Index(fields=["created_at"], name="grid_order_created_150a4d_idx"),
        ),
    ]
