# Generated by Django 4.2.8 on 2025-12-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grid_trading", "0019_gridorder_gridstrategy_gridzone_klinedata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="screeningrecord",
            name="screening_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="标识该筛选对应的交易日期(如2024-12-05)，用于按天分析场景。null表示实时筛选",
                null=True,
                verbose_name="筛选日期",
            ),
        ),
        migrations.AddIndex(
            model_name="screeningrecord",
            index=models.Index(fields=["-screening_date"], name="screening_r_screeni_e1eb1b_idx"),
        ),
    ]
