# Generated by Django 4.2.8 on 2025-12-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grid_trading", "0020_screeningrecord_screening_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="screeningrecord",
            name="filter_max_ma99_slope",
            field=models.FloatField(
                blank=True,
                help_text="EMA99斜率<=此值才会被筛选出来（负值表示下降趋势）",
                null=True,
                verbose_name="EMA99斜率最大值过滤",
            ),
        ),
    ]
