# Generated by Django 4.2.8 on 2025-12-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grid_trading", "0021_screeningrecord_filter_max_ma99_slope"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUpdateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="执行开始时间"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="执行结束时间"),
                ),
                ("contracts_count", models.IntegerField(default=0, verbose_name="更新合约数量")),
                (
                    "klines_count",
                    models.IntegerField(
                        default=0,
                        help_text="所有合约×所有周期的K线总数",
                        verbose_name="获取K线总数",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=10,
                        verbose_name="执行状态",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "execution_seconds",
                    models.IntegerField(blank=True, null=True, verbose_name="执行耗时(秒)"),
                ),
            ],
            options={
                "verbose_name": "数据更新日志",
                "verbose_name_plural": "数据更新日志",
                "db_table": "data_update_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceAlertRule",
            fields=[
                (
                    "rule_id",
                    models.IntegerField(
                        choices=[
                            (1, "7天价格新高(4h)"),
                            (2, "7天价格新低(4h)"),
                            (3, "价格触及MA20"),
                            (4, "价格触及MA99"),
                            (5, "价格达到分布区间90%极值"),
                        ],
                        help_text="1-5对应5种预设规则",
                        primary_key=True,
                        serialize=False,
                        verbose_name="规则ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="规则名称")),
                (
                    "description",
                    models.TextField(help_text="规则的技术说明和判定逻辑", verbose_name="规则描述"),
                ),
                (
                    "enabled",
                    models.BooleanField(db_index=True, default=True, verbose_name="启用状态"),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text='JSON格式的参数配置,如{"ma_threshold": 0.5, "percentile": 90}',
                        verbose_name="规则参数",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "价格触发规则",
                "verbose_name_plural": "价格触发规则",
                "db_table": "price_alert_rule",
            },
        ),
        migrations.CreateModel(
            name="ScriptLock",
            fields=[
                (
                    "lock_name",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="锁名称",
                    ),
                ),
                ("acquired_at", models.DateTimeField(auto_now=True, verbose_name="获取时间")),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
            ],
            options={
                "verbose_name": "脚本锁",
                "verbose_name_plural": "脚本锁",
                "db_table": "script_lock",
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, verbose_name="配置键"
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="支持字符串、数字、JSON等格式", verbose_name="配置值"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="配置说明"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "system_config",
            },
        ),
        migrations.CreateModel(
            name="MonitoredContract",
            fields=[
                (
                    "symbol",
                    models.CharField(
                        help_text="如BTCUSDT",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="合约代码",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "手动添加"), ("auto", "自动筛选")],
                        db_index=True,
                        default="manual",
                        max_length=10,
                        verbose_name="来源",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "启用"), ("disabled", "禁用"), ("expired", "已过期")],
                        db_index=True,
                        default="enabled",
                        max_length=10,
                        verbose_name="监控状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="添加时间")),
                (
                    "last_screening_date",
                    models.DateField(
                        blank=True,
                        help_text="仅自动添加的合约有此字段",
                        null=True,
                        verbose_name="最后筛选出现日期",
                    ),
                ),
                (
                    "last_data_update_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后数据更新时间"),
                ),
            ],
            options={
                "verbose_name": "监控合约",
                "verbose_name_plural": "监控合约",
                "db_table": "monitored_contract",
                "indexes": [
                    models.Index(fields=["source", "status"], name="monitored_c_source_b35cf6_idx"),
                    models.Index(
                        fields=["-last_screening_date"], name="monitored_c_last_sc_41ede5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertTriggerLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20, verbose_name="合约代码")),
                (
                    "rule_id",
                    models.IntegerField(
                        db_index=True, help_text="关联PriceAlertRule.rule_id", verbose_name="规则ID"
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="触发时间"),
                ),
                (
                    "current_price",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="当前价格"),
                ),
                (
                    "pushed",
                    models.BooleanField(db_index=True, default=False, verbose_name="是否已推送"),
                ),
                ("pushed_at", models.DateTimeField(blank=True, null=True, verbose_name="推送时间")),
                (
                    "skip_reason",
                    models.CharField(
                        blank=True,
                        help_text='如"防重复"、"推送失败"等',
                        max_length=100,
                        verbose_name="跳过原因",
                    ),
                ),
                (
                    "extra_info",
                    models.JSONField(
                        default=dict,
                        help_text="存储MA值、7天最高/最低等上下文信息",
                        verbose_name="额外信息",
                    ),
                ),
            ],
            options={
                "verbose_name": "触发日志",
                "verbose_name_plural": "触发日志",
                "db_table": "alert_trigger_log",
                "indexes": [
                    models.Index(
                        fields=["symbol", "rule_id", "-pushed_at"],
                        name="alert_trigg_symbol_176c53_idx",
                    ),
                    models.Index(fields=["-triggered_at"], name="alert_trigg_trigger_fa2ecd_idx"),
                    models.Index(
                        fields=["pushed", "skip_reason", "-triggered_at"],
                        name="alert_trigg_pushed_c58507_idx",
                    ),
                ],
            },
        ),
    ]
