# Generated by Django 4.2.8 on 2025-12-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grid_trading", "0022_create_price_monitor_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="screeningresultmodel",
            name="price_percentile_100",
            field=models.FloatField(
                default=50.0,
                help_text="基于100根4h K线的价格分位，0%=最高点，100%=最低点",
                verbose_name="价格分位(100根4h)",
            ),
        ),
    ]
