# Generated by Django 4.2.8 on 2025-12-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grid_trading", "0024_alter_screeningresultmodel_price_percentile_100"),
    ]

    operations = [
        migrations.AddField(
            model_name="screeningresultmodel",
            name="money_flow_large_dominance",
            field=models.FloatField(
                default=0.0,
                help_text="大单对资金流的影响程度(0-1)，越高表示机构影响越大",
                verbose_name="大单主导度",
            ),
        ),
        migrations.AddField(
            model_name="screeningresultmodel",
            name="money_flow_large_net",
            field=models.FloatField(
                default=0.0,
                help_text="24小时大单净流入金额，正值=流入，负值=流出",
                verbose_name="大单净流入(USDT)",
            ),
        ),
        migrations.AddField(
            model_name="screeningresultmodel",
            name="money_flow_strength",
            field=models.FloatField(
                default=0.5,
                help_text="主动买入占比(0-1)，>0.55=买盘强，<0.45=卖盘强",
                verbose_name="资金流强度",
            ),
        ),
    ]
