# Generated by Django 4.2.8 on 2025-12-12 10:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("grid_trading", "0025_screeningresultmodel_money_flow_large_dominance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "batch_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name="批次ID"),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        null=True,
                        verbose_name="币安交易对",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("mapping_generation", "映射关系生成"),
                            ("mapping_update", "映射关系更新"),
                            ("market_data_update", "市值/FDV数据更新"),
                            ("contract_sync", "合约同步"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("partial_success", "部分成功"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                (
                    "executed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="执行时间"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True, verbose_name="元数据")),
            ],
            options={
                "verbose_name": "更新日志",
                "verbose_name_plural": "更新日志",
                "db_table": "update_log",
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(fields=["batch_id"], name="update_log_batch_idx"),
                    models.Index(fields=["symbol"], name="update_log_symbol_idx"),
                    models.Index(fields=["operation_type"], name="update_log_operation_idx"),
                    models.Index(fields=["status"], name="update_log_status_idx"),
                    models.Index(fields=["executed_at"], name="update_log_executed_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TokenMapping",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "symbol",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="币安交易对"
                    ),
                ),
                ("base_token", models.CharField(max_length=10, verbose_name="基础代币")),
                (
                    "coingecko_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="CoinGecko ID",
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("auto_matched", "自动匹配"),
                            ("manual_confirmed", "人工确认"),
                            ("needs_review", "需要审核"),
                        ],
                        db_index=True,
                        default="needs_review",
                        max_length=20,
                        verbose_name="匹配状态",
                    ),
                ),
                (
                    "alternatives",
                    models.JSONField(blank=True, null=True, verbose_name="候选ID列表"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "代币映射",
                "verbose_name_plural": "代币映射",
                "db_table": "token_mapping",
                "ordering": ["symbol"],
                "indexes": [
                    models.Index(fields=["symbol"], name="token_mapping_symbol_idx"),
                    models.Index(fields=["match_status"], name="token_mapping_status_idx"),
                    models.Index(fields=["coingecko_id"], name="token_mapping_cg_id_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "symbol",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="币安交易对"
                    ),
                ),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="市值(USD)",
                    ),
                ),
                (
                    "fully_diluted_valuation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="FDV(USD)",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(default="coingecko", max_length=50, verbose_name="数据来源"),
                ),
                ("fetched_at", models.DateTimeField(verbose_name="获取时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "市场数据",
                "verbose_name_plural": "市场数据",
                "db_table": "market_data",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["symbol"], name="market_data_symbol_idx"),
                    models.Index(fields=["updated_at"], name="market_data_updated_idx"),
                ],
            },
        ),
    ]
