# Generated by Django 4.2.8 on 2025-12-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grid_trading", "0026_add_market_cap_fdv_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingRateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True, help_text="如: BTCUSDT", max_length=20, verbose_name="交易对"
                    ),
                ),
                (
                    "funding_rate",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="正值表示多头支付空头，负值表示空头支付多头",
                        max_digits=20,
                        verbose_name="资金费率",
                    ),
                ),
                (
                    "funding_time",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="币安资金费率结算时间",
                        verbose_name="结算时间戳(毫秒)",
                    ),
                ),
                (
                    "funding_interval_hours",
                    models.IntegerField(
                        default=8,
                        help_text="标准合约8小时，高频合约可能是1小时或4小时",
                        verbose_name="结算周期(小时)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="数据入库时间", verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "历史资金费率",
                "verbose_name_plural": "历史资金费率",
                "db_table": "grid_funding_rate_history",
                "ordering": ["-funding_time"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "funding_time"], name="grid_fundin_symbol_fc6dc8_idx"
                    ),
                    models.Index(fields=["funding_time"], name="grid_fundin_funding_e7737d_idx"),
                ],
                "unique_together": {("symbol", "funding_time")},
            },
        ),
    ]
