# Generated by Django 4.2.8 on 2025-11-06 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(help_text='交易所提供的唯一ID', max_length=200, unique=True, verbose_name='公告ID')),
                ('title', models.CharField(max_length=1000, verbose_name='公告标题')),
                ('description', models.TextField(blank=True, verbose_name='公告描述')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='公告URL')),
                ('announced_at', models.DateTimeField(verbose_name='发布时间')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分类')),
                ('processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'announcements',
                'ordering': ['-announced_at'],
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='交易所名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='交易所代码')),
                ('announcement_url', models.URLField(blank=True, max_length=500, verbose_name='公告URL')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '交易所',
                'verbose_name_plural': '交易所',
                'db_table': 'exchanges',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_symbol', models.CharField(help_text='如BTC, ETH', max_length=50, verbose_name='币种代码')),
                ('coin_name', models.CharField(blank=True, help_text='如Bitcoin', max_length=200, verbose_name='币种全称')),
                ('listing_type', models.CharField(choices=[('spot', '现货'), ('futures', '合约'), ('both', '现货+合约')], max_length=50, verbose_name='上线类型')),
                ('confidence', models.FloatField(help_text='0.0-1.0之间的浮点数', verbose_name='识别置信度')),
                ('status', models.CharField(choices=[('pending_review', '待审核'), ('confirmed', '已确认'), ('ignored', '已忽略')], default='pending_review', max_length=50, verbose_name='状态')),
                ('identified_at', models.DateTimeField(verbose_name='识别时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='monitor.announcement', verbose_name='关联公告')),
            ],
            options={
                'verbose_name': '新币上线',
                'verbose_name_plural': '新币上线',
                'db_table': 'listings',
                'ordering': ['-identified_at'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='monitor.exchange', verbose_name='交易所'),
        ),
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('webhook', 'Webhook'), ('telegram', 'Telegram'), ('email', 'Email')], max_length=50, verbose_name='通知渠道')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('success', '发送成功'), ('failed', '发送失败')], max_length=50, verbose_name='发送状态')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='成功发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_records', to='monitor.listing', verbose_name='关联新币上线')),
            ],
            options={
                'verbose_name': '通知记录',
                'verbose_name_plural': '通知记录',
                'db_table': 'notification_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing'], name='idx_notif_listing'), models.Index(fields=['status'], name='idx_notif_status'), models.Index(fields=['created_at'], name='idx_notif_created')],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='idx_listing_status'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['coin_symbol'], name='idx_coin_symbol'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['identified_at'], name='idx_identified'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['announcement'], name='idx_listing_announcement'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['exchange', 'announced_at'], name='idx_exchange_announced'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['processed'], name='idx_processed'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_at'], name='idx_created'),
        ),
    ]
