# Generated by Django 4.2.8 on 2025-11-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='如BTCUSDT', max_length=50, verbose_name='合约代码')),
                ('contract_type', models.CharField(choices=[('perpetual', '永续合约')], default='perpetual', max_length=50, verbose_name='合约类型')),
                ('status', models.CharField(choices=[('active', '活跃'), ('delisted', '已下线')], default='active', max_length=50, verbose_name='状态')),
                ('current_price', models.DecimalField(decimal_places=8, help_text='Mark Price或Last Price', max_digits=20, verbose_name='当前价格')),
                ('first_seen', models.DateTimeField(help_text='用于检测新合约上线', verbose_name='首次发现时间')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futures_contracts', to='monitor.exchange', verbose_name='交易所')),
            ],
            options={
                'verbose_name': '合约',
                'verbose_name_plural': '合约',
                'db_table': 'futures_contracts',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='FuturesListingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('webhook', 'Webhook'), ('telegram', 'Telegram'), ('email', 'Email')], max_length=50, verbose_name='通知渠道')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('success', '发送成功'), ('failed', '发送失败')], default='pending', max_length=50, verbose_name='发送状态')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='成功发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('futures_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_notifications', to='monitor.futurescontract', verbose_name='关联合约')),
            ],
            options={
                'verbose_name': '合约上线通知记录',
                'verbose_name_plural': '合约上线通知记录',
                'db_table': 'futures_listing_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['futures_contract'], name='idx_futures_notif_contract'), models.Index(fields=['status'], name='idx_futures_notif_status'), models.Index(fields=['created_at'], name='idx_futures_notif_created')],
            },
        ),
        migrations.AddIndex(
            model_name='futurescontract',
            index=models.Index(fields=['exchange', 'status'], name='idx_futures_exchange_status'),
        ),
        migrations.AddIndex(
            model_name='futurescontract',
            index=models.Index(fields=['symbol'], name='idx_futures_symbol'),
        ),
        migrations.AddIndex(
            model_name='futurescontract',
            index=models.Index(fields=['status'], name='idx_futures_status'),
        ),
        migrations.AddIndex(
            model_name='futurescontract',
            index=models.Index(fields=['first_seen'], name='idx_futures_first_seen'),
        ),
        migrations.AddIndex(
            model_name='futurescontract',
            index=models.Index(fields=['last_updated'], name='idx_futures_last_updated'),
        ),
        migrations.AlterUniqueTogether(
            name='futurescontract',
            unique_together={('exchange', 'symbol')},
        ),
    ]
