# Generated by Django 4.2.8 on 2025-11-11 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_futurescontract_futureslistingnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesMarketIndicators',
            fields=[
                ('futures_contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='market_indicators', serialize=False, to='monitor.futurescontract', verbose_name='关联合约')),
                ('open_interest', models.DecimalField(blank=True, decimal_places=8, help_text='当前未平仓合约总量', max_digits=30, null=True, verbose_name='持仓量')),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=8, help_text='过去24小时的总交易量', max_digits=30, null=True, verbose_name='24小时交易量')),
                ('funding_rate', models.DecimalField(blank=True, decimal_places=6, help_text='当前周期的资金费率', max_digits=10, null=True, verbose_name='当前资金费率')),
                ('funding_rate_annual', models.DecimalField(blank=True, decimal_places=4, help_text='根据当前费率和间隔计算的年化收益率', max_digits=10, null=True, verbose_name='年化资金费率')),
                ('next_funding_time', models.DateTimeField(blank=True, help_text='下一次资金费率结算的时间', null=True, verbose_name='下次结算时间')),
                ('funding_interval_hours', models.IntegerField(default=8, help_text='资金费率结算的时间间隔', verbose_name='资金费率间隔(小时)')),
                ('funding_rate_cap', models.DecimalField(blank=True, decimal_places=6, help_text='资金费率的最大值限制', max_digits=10, null=True, verbose_name='资金费率上限')),
                ('funding_rate_floor', models.DecimalField(blank=True, decimal_places=6, help_text='资金费率的最小值限制', max_digits=10, null=True, verbose_name='资金费率下限')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '合约市场指标',
                'verbose_name_plural': '合约市场指标',
                'db_table': 'futures_market_indicators',
                'indexes': [models.Index(fields=['open_interest'], name='idx_market_oi'), models.Index(fields=['volume_24h'], name='idx_market_volume'), models.Index(fields=['funding_rate'], name='idx_market_funding'), models.Index(fields=['last_updated'], name='idx_market_updated')],
            },
        ),
    ]
