# Generated by Django 4.2.8 on 2025-12-25 06:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0003_futuresmarketindicators"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="现货交易对代码，如BTC/USDT、ETH/USDT",
                        max_length=50,
                        verbose_name="交易对代码",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "活跃"), ("delisted", "已下线")],
                        default="active",
                        max_length=50,
                        verbose_name="状态",
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="当前标记价格或最后成交价格",
                        max_digits=20,
                        verbose_name="当前价格",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="用于检测新交易对上线",
                        verbose_name="首次发现时间",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True, verbose_name="最后更新时间")),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spot_contracts",
                        to="monitor.exchange",
                        verbose_name="交易所",
                    ),
                ),
            ],
            options={
                "verbose_name": "现货交易对",
                "verbose_name_plural": "现货交易对",
                "db_table": "spot_contracts",
                "ordering": ["-last_updated"],
                "indexes": [
                    models.Index(fields=["exchange", "status"], name="idx_spot_exchange_status"),
                    models.Index(fields=["symbol"], name="idx_spot_symbol"),
                    models.Index(fields=["status"], name="idx_spot_status"),
                    models.Index(fields=["first_seen"], name="idx_spot_first_seen"),
                    models.Index(fields=["last_updated"], name="idx_spot_last_updated"),
                ],
                "unique_together": {("exchange", "symbol")},
            },
        ),
    ]
