"""
Django settings for listing_monitor_project project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from decimal import Decimal
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mh^_&xxx)1u3%j_ko!8)js23cbo785w*jvtb_4l!2xs$5+z6mt'

# SECURITY WARNING: don't run with debug turned on in production!
# 生产环境应设置为 False
DEBUG = True

# 允许的主机/域名
# 生产环境：添加服务器IP和域名
# 开发环境：localhost即可
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '45.207.228.38',  # 生产服务器IP
    # 如果有域名，也添加进来：
    # 'yourdomain.com',
    # 'www.yourdomain.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    # Local apps
    'monitor',
    'twitter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'listing_monitor_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'listing_monitor_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Logging Configuration
# https://docs.djangoproject.com/en/4.2/topics/logging/

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_futures': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'futures_updates.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'file_general': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'general.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
        },
    },
    'loggers': {
        # Django系统日志
        'django': {
            'handlers': ['console', 'file_general'],
            'level': 'INFO',
            'propagate': False,
        },
        # 合约更新相关日志
        'monitor.services.futures_fetcher': {
            'handlers': ['console', 'file_futures'],
            'level': 'INFO',
            'propagate': False,
        },
        'monitor.api_clients': {
            'handlers': ['console', 'file_futures'],
            'level': 'INFO',
            'propagate': False,
        },
        'monitor.management.commands.update_futures_prices': {
            'handlers': ['console', 'file_futures'],
            'level': 'INFO',
            'propagate': False,
        },
        # 其他monitor应用日志
        'monitor': {
            'handlers': ['console', 'file_general'],
            'level': 'INFO',
            'propagate': False,
        },
        # Twitter应用日志
        'twitter': {
            'handlers': ['console', 'file_general'],
            'level': 'INFO',
            'propagate': False,
        },
        'twitter.sdk': {
            'handlers': ['console', 'file_general'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'twitter.services': {
            'handlers': ['console', 'file_general'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file_general'],
        'level': 'INFO',
    },
}


# =============================================================================
# Twitter 应用配置
# =============================================================================

# Twitter API 配置
TWITTER_API_BASE_URL = os.getenv('TWITTER_API_BASE_URL', 'https://api.apidance.pro')
# 默认使用项目配置的有效 API Key，避免线上环境未配置时报错
TWITTER_API_KEY = os.getenv('TWITTER_API_KEY', 'jv58xo5oyj6h4bvtw02gsqav40brrd')

# DeepSeek AI 配置（万界数据代理）
# 官方文档：https://maas-openapi.wanjiedata.com/
# 认证方式：Authorization: Bearer {API_KEY}
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA5NjIzMjgsImtleSI6IjVLNzVaOFROQzlGNEhNMzdQOVk3In0.z2zrH54Ip8aQeEk_dWMizomkERENlkNuyV8jOa1glXg')
DEEPSEEK_BASE_URL = os.getenv('DEEPSEEK_BASE_URL', 'https://maas-openapi.wanjiedata.com/api/v1/')
DEEPSEEK_MODEL = os.getenv('DEEPSEEK_MODEL', 'deepseek-v3')

# AI 分析成本限制配置
MAX_COST_PER_ANALYSIS = Decimal(os.getenv('MAX_COST_PER_ANALYSIS', '10.00'))  # 单次分析最大成本（美元）
COST_ALERT_THRESHOLD = Decimal(os.getenv('COST_ALERT_THRESHOLD', '5.00'))  # 成本告警阈值（美元）

# Twitter API 限流配置
TWITTER_RATE_LIMIT_PER_MINUTE = int(os.getenv('TWITTER_RATE_LIMIT_PER_MINUTE', '50'))
TWITTER_MAX_RETRY_ATTEMPTS = int(os.getenv('TWITTER_MAX_RETRY_ATTEMPTS', '3'))

# 默认批次大小
TWITTER_DEFAULT_BATCH_SIZE = int(os.getenv('TWITTER_DEFAULT_BATCH_SIZE', '500'))
AI_ANALYSIS_BATCH_SIZE = int(os.getenv('AI_ANALYSIS_BATCH_SIZE', '100'))
