"""
Django settings for listing_monitor_project project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from decimal import Decimal
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mh^_&xxx)1u3%j_ko!8)js23cbo785w*jvtb_4l!2xs$5+z6mt'

# SECURITY WARNING: don't run with debug turned on in production!
# 生产环境应设置为 False
# 从环境变量读取，默认开发环境为True
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

# 允许的主机/域名
# 生产环境：添加服务器IP和域名
# 开发环境：localhost即可
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '45.207.228.38',  # 旧生产服务器IP
    '43.157.38.74',   # 新生产服务器IP
    '*',              # 允许所有主机（仅用于runserver部署）
    # 如果有域名，也添加进来：
    # 'yourdomain.com',
    # 'www.yourdomain.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    # Local apps
    'monitor',
    'twitter',
    'vp_squeeze',
    'grid_trading',  # 网格交易系统
    'backtest',      # 回测框架
    'volume_trap',   # 巨量诱多/弃盘检测系统 (迭代002)
    'ddps_z',        # 动态偏离概率空间 (迭代009)
    'strategy_adapter',  # 策略适配层 (迭代013)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'listing_monitor_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'listing_monitor_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic收集的静态文件目录

# Media files (User uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Logging Configuration
# https://docs.djangoproject.com/en/4.2/topics/logging/

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_futures': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'futures_updates.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'file_general': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'general.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
        },
    },
    'loggers': {
        # Django系统日志
        'django': {
            'handlers': ['console', 'file_general'],
            'level': 'INFO',
            'propagate': False,
        },
        # 合约更新相关日志
        'monitor.services.futures_fetcher': {
            'handlers': ['console', 'file_futures'],
            'level': 'INFO',
            'propagate': False,
        },
        'monitor.api_clients': {
            'handlers': ['console', 'file_futures'],
            'level': 'INFO',
            'propagate': False,
        },
        'monitor.management.commands.update_futures_prices': {
            'handlers': ['console', 'file_futures'],
            'level': 'INFO',
            'propagate': False,
        },
        # 其他monitor应用日志
        'monitor': {
            'handlers': ['console', 'file_general'],
            'level': 'INFO',
            'propagate': False,
        },
        # Twitter应用日志
        'twitter': {
            'handlers': ['console', 'file_general'],
            'level': 'INFO',
            'propagate': False,
        },
        'twitter.sdk': {
            'handlers': ['console', 'file_general'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'twitter.services': {
            'handlers': ['console', 'file_general'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file_general'],
        'level': 'INFO',
    },
}


# =============================================================================
# Twitter 应用配置
# =============================================================================

# Twitter API 配置
TWITTER_API_BASE_URL = os.getenv('TWITTER_API_BASE_URL', 'https://api.apidance.pro')
# 默认使用项目配置的有效 API Key，避免线上环境未配置时报错
TWITTER_API_KEY = os.getenv('TWITTER_API_KEY', 'jv58xo5oyj6h4bvtw02gsqav40brrd')

# DeepSeek AI 配置（万界数据代理）
# 官方文档：https://maas-openapi.wanjiedata.com/
# 认证方式：Authorization: Bearer {API_KEY}
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA5NjIzMjgsImtleSI6IjVLNzVaOFROQzlGNEhNMzdQOVk3In0.z2zrH54Ip8aQeEk_dWMizomkERENlkNuyV8jOa1glXg')
DEEPSEEK_BASE_URL = os.getenv('DEEPSEEK_BASE_URL', 'https://maas-openapi.wanjiedata.com/api/v1/')
DEEPSEEK_MODEL = os.getenv('DEEPSEEK_MODEL', 'deepseek-v3')

# AI 分析成本限制配置
MAX_COST_PER_ANALYSIS = Decimal(os.getenv('MAX_COST_PER_ANALYSIS', '10.00'))  # 单次分析最大成本（美元）
COST_ALERT_THRESHOLD = Decimal(os.getenv('COST_ALERT_THRESHOLD', '5.00'))  # 成本告警阈值（美元）

# Twitter API 限流配置
TWITTER_RATE_LIMIT_PER_MINUTE = int(os.getenv('TWITTER_RATE_LIMIT_PER_MINUTE', '50'))
TWITTER_MAX_RETRY_ATTEMPTS = int(os.getenv('TWITTER_MAX_RETRY_ATTEMPTS', '3'))

# 默认批次大小
TWITTER_DEFAULT_BATCH_SIZE = int(os.getenv('TWITTER_DEFAULT_BATCH_SIZE', '500'))
AI_ANALYSIS_BATCH_SIZE = int(os.getenv('AI_ANALYSIS_BATCH_SIZE', '100'))

# =============================================================================
# CoinGecko API 配置（用于市值/FDV数据获取）
# =============================================================================
# CoinGecko API Key - Feature 008: Market Cap & FDV Display
# 默认使用项目API Key，无需在每个环境单独配置
COINGECKO_API_KEY = 'CG-S9WAcfdu3ENrRmeAwP53iGj7'

# =============================================================================
# 巨量诱多/弃盘检测系统配置 (Volume Trap Detection System Configuration)
# =============================================================================
"""
巨量诱多/弃盘检测系统的参数配置。

本配置字典定义了三阶段状态机检测的核心阈值参数：
- 阶段1（Discovery）：异常放量发现的触发参数
- 阶段2（Confirmation）：逃离识别的确认参数
- 阶段3（Validation）：长期特征锁定的验证参数

所有参数均支持通过环境变量覆盖，便于不同环境的测试和调优。
环境变量命名规则：VT_{参数名}，例如 VT_RVOL_THRESHOLD=10

Related:
    - PRD: docs/iterations/002-volume-trap-detection/prd.md (第二部分-2.4节)
    - Architecture: docs/iterations/002-volume-trap-detection/architecture.md
    - Task: TASK-002-002
"""


def _get_volume_trap_config_value(key, default, value_type, min_val=None, max_val=None):
    """获取巨量诱多检测系统配置参数，支持环境变量覆盖和边界检查。

    Args:
        key (str): 配置参数键名
        default: 默认值
        value_type (type): 目标类型（int/float/str）
        min_val (float, optional): 最小值边界（用于数值类型）
        max_val (float, optional): 最大值边界（用于比例类型）

    Returns:
        配置参数的最终值（可能来自环境变量或默认值）

    Raises:
        ValueError: 当环境变量类型转换失败或边界检查不通过时

    Examples:
        >>> _get_volume_trap_config_value('RVOL_THRESHOLD', 8, int, min_val=1)
        8
        >>> os.environ['VT_RVOL_THRESHOLD'] = 'abc'
        >>> _get_volume_trap_config_value('RVOL_THRESHOLD', 8, int)
        ValueError: VT_RVOL_THRESHOLD环境变量类型错误: 预期类型=int, 实际值='abc'
    """
    env_key = f'VT_{key}'
    env_value = os.getenv(env_key)

    if env_value is None:
        return default

    # 类型转换与Fail-Fast异常处理
    try:
        if value_type == int:
            value = int(env_value)
        elif value_type == float:
            value = float(env_value)
        elif value_type == str:
            value = env_value
        else:
            value = env_value
    except (ValueError, TypeError) as e:
        raise ValueError(
            f"{env_key}环境变量类型错误: "
            f"预期类型={value_type.__name__}, 实际值='{env_value}'"
        )

    # 边界检查（Fail-Fast）
    if value_type in (int, float):
        if min_val is not None and value < min_val:
            raise ValueError(
                f"{env_key}参数边界错误: "
                f"预期>={min_val}, 实际值={value}"
            )
        if max_val is not None and value > max_val:
            raise ValueError(
                f"{env_key}参数边界错误: "
                f"预期<={max_val}, 实际值={value}"
            )

    return value


VOLUME_TRAP_CONFIG = {
    # === 阶段1：异常放量发现 (Discovery Phase) ===

    # RVOL触发倍数
    # 物理意义：当前成交量需达到20期均线的8倍才触发警报
    # 单位：倍数
    # 默认值理由：基于历史数据统计，8倍是识别异常放量的合理阈值
    'RVOL_THRESHOLD': _get_volume_trap_config_value(
        'RVOL_THRESHOLD', 8, int, min_val=1
    ),

    # 振幅触发倍数
    # 物理意义：当前振幅需达到过去30根K线均值的3倍
    # 单位：倍数
    # 默认值理由：3倍振幅异常足以识别脉冲行为
    'AMPLITUDE_THRESHOLD': _get_volume_trap_config_value(
        'AMPLITUDE_THRESHOLD', 3, int, min_val=1
    ),

    # 上影线比例阈值
    # 物理意义：上影线占整根K线长度的最小比例
    # 单位：比例（0-1）
    # 默认值理由：50%上影线表明价格被快速压制，是诱多信号
    'UPPER_SHADOW_THRESHOLD': _get_volume_trap_config_value(
        'UPPER_SHADOW_THRESHOLD', 0.5, float, min_val=0, max_val=1
    ),

    # === 阶段2：逃离识别 (Confirmation Phase) ===

    # 成交量留存率阈值
    # 物理意义：触发后平均成交量需低于触发成交量的15%
    # 单位：百分比
    # 默认值理由：低于15%表明买盘极度匮乏，资金已撤离
    'VOLUME_RETENTION_THRESHOLD': _get_volume_trap_config_value(
        'VOLUME_RETENTION_THRESHOLD', 15, int, min_val=0, max_val=100
    ),

    # PE（价差效率）异常倍数
    # 物理意义：当前PE需达到历史30天均值的2倍
    # 单位：倍数
    # 默认值理由：2倍表明卖盘深度极薄，买盘已撤离
    'PE_MULTIPLIER': _get_volume_trap_config_value(
        'PE_MULTIPLIER', 2, int, min_val=1
    ),

    # === 阶段3：长期特征锁定 (Validation Phase) ===

    # OBV背离检测窗口
    # 物理意义：检测最近5根K线内是否出现底背离
    # 单位：K线数量
    # 默认值理由：5根K线足以识别短期资金流向变化
    'OBV_LOOKBACK_PERIODS': _get_volume_trap_config_value(
        'OBV_LOOKBACK_PERIODS', 5, int, min_val=3, max_val=20
    ),

    # ATR压缩阈值
    # 物理意义：当前ATR需低于历史基线的50%
    # 单位：比例（0-1）
    # 默认值理由：低于0.5表明波动率显著压缩，市场进入冷却期
    'ATR_COMPRESSION_THRESHOLD': _get_volume_trap_config_value(
        'ATR_COMPRESSION_THRESHOLD', 0.5, float, min_val=0, max_val=1
    ),

    # === 系统配置 ===

    # 默认监控周期
    # 物理意义：系统默认使用的K线周期
    # 单位：时间标识符（'1h'/'4h'/'1d'）
    # 默认值理由：4h周期在灵敏度和噪音过滤之间取得平衡
    'DEFAULT_INTERVAL': _get_volume_trap_config_value(
        'DEFAULT_INTERVAL', '4h', str
    ),

    # 数据保留天数
    # 物理意义：监控记录的保留周期
    # 单位：天
    # 默认值理由：180天覆盖约6个月，足以进行策略回测
    'RETENTION_DAYS': _get_volume_trap_config_value(
        'RETENTION_DAYS', 180, int, min_val=30
    ),
}

# =============================================================================
# 动态偏离概率空间配置 (DDPS-Z Configuration) - 迭代009
# =============================================================================
"""
动态偏离概率空间2.0系统的参数配置。

基于EWMA Z-Score的波动率自适应标准化系统，通过统计方法将不同币种的
价格偏离转化为统一的"统计罕见程度"，实现跨币种可比的超买/超卖信号识别。

Related:
    - PRD: docs/iterations/009-ddps-z-probability-engine/prd.md
    - Architecture: docs/iterations/009-ddps-z-probability-engine/architecture.md
"""

DDPS_CONFIG = {
    # EMA均线周期
    # 物理意义：用于计算基础偏离率的指数移动平均线周期
    # 单位：K线数量
    # 默认值理由：EMA25是加密货币交易中常用的均线周期
    'EMA_PERIOD': int(os.getenv('DDPS_EMA_PERIOD', '25')),

    # EWMA窗口大小N
    # 物理意义：EWMA衰减因子α = 2/(N+1)，N越大越平滑
    # 单位：K线数量
    # 默认值理由：180根4h K线约30天，覆盖完整市场周期
    'EWMA_WINDOW_N': int(os.getenv('DDPS_EWMA_WINDOW_N', '180')),

    # 默认K线周期
    # 物理意义：系统默认使用的K线周期
    # 单位：时间标识符
    # 默认值理由：4h周期平衡信号灵敏度和噪声过滤
    'DEFAULT_INTERVAL': os.getenv('DDPS_DEFAULT_INTERVAL', '4h'),

    # 放量判断阈值
    # 物理意义：RVOL需达到此倍数才视为"放量"
    # 单位：倍数
    # 默认值理由：2倍阈值能捕捉更多有效信号
    'RVOL_THRESHOLD': float(os.getenv('DDPS_RVOL_THRESHOLD', '2.0')),

    # 最少K线数量要求
    # 物理意义：计算EWMA所需的最少K线数量
    # 单位：K线数量
    # 默认值理由：与EWMA_WINDOW_N保持一致
    'MIN_KLINES_REQUIRED': int(os.getenv('DDPS_MIN_KLINES_REQUIRED', '180')),

    # 超卖Z值阈值（5%分位）
    # 物理意义：低于此Z值视为超卖
    # 单位：标准差
    # 默认值理由：-1.64对应正态分布5%分位
    'Z_SCORE_OVERSOLD': float(os.getenv('DDPS_Z_SCORE_OVERSOLD', '-1.64')),

    # 超买Z值阈值（95%分位）
    # 物理意义：高于此Z值视为超买
    # 单位：标准差
    # 默认值理由：1.64对应正态分布95%分位
    'Z_SCORE_OVERBOUGHT': float(os.getenv('DDPS_Z_SCORE_OVERBOUGHT', '1.64')),

    # RVOL计算回溯周期
    # 物理意义：计算成交量均值的历史窗口
    # 单位：K线数量
    # 默认值理由：20周期是标准成交量均线周期
    'RVOL_LOOKBACK_PERIOD': int(os.getenv('DDPS_RVOL_LOOKBACK_PERIOD', '20')),

    # β宏观周期阈值配置（前端显示值，原始值需/100）
    # 物理意义：用于判断市场处于何种趋势周期
    # 单位：β值（前端显示值）
    'BETA_CYCLE_THRESHOLDS': {
        # 上涨预警阈值：β > 600 且增加时触发
        'bull_warning': int(os.getenv('DDPS_BETA_BULL_WARNING', '600')),
        # 强势上涨确认阈值：β > 1000 时确认
        'bull_strong': int(os.getenv('DDPS_BETA_BULL_STRONG', '1000')),
        # 下跌预警阈值：β < -600 且减少时触发
        'bear_warning': int(os.getenv('DDPS_BETA_BEAR_WARNING', '-600')),
        # 强势下跌确认阈值：β < -1000 时确认
        'bear_strong': int(os.getenv('DDPS_BETA_BEAR_STRONG', '-1000')),
        # 周期结束阈值：β 跨越此值时周期结束
        'cycle_end': int(os.getenv('DDPS_BETA_CYCLE_END', '0')),
    },
}

# =============================================================================
# DDPS价格监控服务配置 (DDPS Monitor Service Configuration) - 迭代023
# =============================================================================
"""
DDPS价格监控服务的参数配置。

定时运行的监控服务，每4小时自动：
1. 更新指定交易对的K线数据
2. 计算DDPS指标和策略信号
3. 推送市场状态和交易信号到指定channel

Related:
    - PRD: docs/iterations/023-ddps-price-monitor/prd.md
    - Architecture: docs/iterations/023-ddps-price-monitor/architecture.md
"""

DDPS_MONITOR_CONFIG = {
    # 默认监控交易对列表
    # 物理意义：不指定--symbols时使用的交易对
    # 单位：交易对符号列表
    'default_symbols': [
        'ETHUSDT',
        'BTCUSDT',
        'HYPEUSDT',
        'BNBUSDT',
        'SOLUSDT',
        'SUIUSDT',
    ],

    # 默认策略ID
    # 物理意义：监控使用的策略
    # 单位：策略ID
    # 默认值理由：策略7是最新优化的动态周期自适应策略
    'default_strategy': int(os.getenv('DDPS_MONITOR_STRATEGY', '7')),

    # 推送Channel名称
    # 物理意义：慧诚平台的推送渠道
    'push_channel': os.getenv('DDPS_MONITOR_PUSH_CHANNEL', 'price_ddps'),

    # 推送Token
    # 物理意义：慧诚平台的认证Token
    'push_token': os.getenv('DDPS_MONITOR_PUSH_TOKEN', '6020867bc6334c609d4f348c22f90f14'),

    # K线周期
    # 物理意义：监控使用的K线周期
    # 单位：时间标识符
    'interval': os.getenv('DDPS_MONITOR_INTERVAL', '4h'),

    # 市场类型
    # 物理意义：监控的市场类型（期货/现货）
    'market_type': os.getenv('DDPS_MONITOR_MARKET_TYPE', 'futures'),
}
