# Generated by Django 4.2.8 on 2025-12-24 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monitor", "0003_futuresmarketindicators"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolumeTrapMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("1h", "1小时"), ("4h", "4小时"), ("1d", "1天")],
                        default="4h",
                        help_text="K线周期",
                        max_length=10,
                    ),
                ),
                ("trigger_time", models.DateTimeField(db_index=True, verbose_name="触发时间")),
                (
                    "trigger_price",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="触发价格"),
                ),
                (
                    "trigger_volume",
                    models.DecimalField(decimal_places=8, max_digits=30, verbose_name="触发成交量"),
                ),
                (
                    "trigger_kline_high",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="触发K线最高价"
                    ),
                ),
                (
                    "trigger_kline_low",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="触发K线最低价"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待观察"),
                            ("suspected_abandonment", "疑似弃盘"),
                            ("confirmed_abandonment", "确定弃盘"),
                            ("invalidated", "失效"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("phase_1_passed", models.BooleanField(default=True, verbose_name="阶段1通过")),
                ("phase_2_passed", models.BooleanField(default=False, verbose_name="阶段2通过")),
                ("phase_3_passed", models.BooleanField(default=False, verbose_name="阶段3通过")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "futures_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volume_trap_monitors",
                        to="monitor.futurescontract",
                        verbose_name="关联合约",
                    ),
                ),
            ],
            options={
                "verbose_name": "量价异常监控",
                "verbose_name_plural": "量价异常监控",
                "db_table": "volume_trap_monitor",
                "ordering": ["-trigger_time"],
            },
        ),
        migrations.CreateModel(
            name="VolumeTrapIndicators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("snapshot_time", models.DateTimeField(db_index=True, verbose_name="快照时间")),
                (
                    "kline_close_price",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="K线收盘价"),
                ),
                (
                    "rvol_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="当前成交量 / MA(V,20)",
                        max_digits=10,
                        null=True,
                        verbose_name="RVOL倍数",
                    ),
                ),
                (
                    "amplitude_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="当前振幅 / 过去30根均值",
                        max_digits=10,
                        null=True,
                        verbose_name="振幅倍数",
                    ),
                ),
                (
                    "upper_shadow_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="(最高-收盘)/(最高-最低) * 100",
                        max_digits=5,
                        null=True,
                        verbose_name="上影线比例",
                    ),
                ),
                (
                    "volume_retention_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="avg(V_post) / V_trigger * 100",
                        max_digits=5,
                        null=True,
                        verbose_name="成交量留存率",
                    ),
                ),
                (
                    "key_level_breach",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="关键位跌破"
                    ),
                ),
                (
                    "price_efficiency",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="|ΔPrice| / Volume",
                        max_digits=20,
                        null=True,
                        verbose_name="价差效率",
                    ),
                ),
                (
                    "ma7",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True, verbose_name="MA(7)"
                    ),
                ),
                (
                    "ma25",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="MA(25)",
                    ),
                ),
                (
                    "ma25_slope",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="MA(25)斜率",
                    ),
                ),
                (
                    "obv",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=30, null=True, verbose_name="OBV"
                    ),
                ),
                (
                    "obv_divergence",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="OBV底背离"
                    ),
                ),
                (
                    "atr",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True, verbose_name="ATR"
                    ),
                ),
                (
                    "atr_compression",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="ATR压缩"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="volume_trap.volumetrapmonitor",
                        verbose_name="关联监控记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "量价异常指标快照",
                "verbose_name_plural": "量价异常指标快照",
                "db_table": "volume_trap_indicators",
                "ordering": ["monitor", "-snapshot_time"],
            },
        ),
        migrations.CreateModel(
            name="VolumeTrapStateTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("from_status", models.CharField(max_length=30, verbose_name="原状态")),
                ("to_status", models.CharField(max_length=30, verbose_name="新状态")),
                (
                    "trigger_condition",
                    models.JSONField(
                        help_text="记录触发状态变更的具体指标值", verbose_name="触发条件"
                    ),
                ),
                ("transition_time", models.DateTimeField(verbose_name="转换时间")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_transitions",
                        to="volume_trap.volumetrapmonitor",
                        verbose_name="关联监控记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "状态转换日志",
                "verbose_name_plural": "状态转换日志",
                "db_table": "volume_trap_state_transition",
                "ordering": ["monitor", "transition_time"],
                "indexes": [
                    models.Index(
                        fields=["monitor", "transition_time"], name="idx_vt_trans_monitor_time"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="volumetrapmonitor",
            index=models.Index(fields=["status", "-trigger_time"], name="idx_vt_status_time"),
        ),
        migrations.AddIndex(
            model_name="volumetrapmonitor",
            index=models.Index(
                fields=["futures_contract", "status"], name="idx_vt_contract_status"
            ),
        ),
        migrations.AddIndex(
            model_name="volumetrapmonitor",
            index=models.Index(fields=["interval", "status"], name="idx_vt_interval_status"),
        ),
        migrations.AlterUniqueTogether(
            name="volumetrapmonitor",
            unique_together={("futures_contract", "interval", "trigger_time")},
        ),
        migrations.AddIndex(
            model_name="volumetrapindicators",
            index=models.Index(
                fields=["monitor", "-snapshot_time"], name="idx_vt_ind_monitor_time"
            ),
        ),
    ]
