# Generated by Django 4.2.8 on 2025-12-25 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0004_create_spot_contract"),
        ("volume_trap", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="volumetrapmonitor",
            unique_together={("futures_contract", "interval", "trigger_time")},
        ),
        migrations.AddField(
            model_name="volumetrapmonitor",
            name="market_type",
            field=models.CharField(
                choices=[("spot", "现货"), ("futures", "合约")],
                db_index=True,
                default="futures",
                help_text="市场类型：现货或合约",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="volumetrapmonitor",
            name="spot_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volume_trap_monitors",
                to="monitor.spotcontract",
                verbose_name="关联现货交易对",
            ),
        ),
        migrations.AlterField(
            model_name="volumetrapmonitor",
            name="futures_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volume_trap_monitors",
                to="monitor.futurescontract",
                verbose_name="关联合约",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="volumetrapmonitor",
            unique_together={
                ("spot_contract", "interval", "trigger_time"),
                ("futures_contract", "interval", "trigger_time"),
            },
        ),
        migrations.AddIndex(
            model_name="volumetrapmonitor",
            index=models.Index(fields=["spot_contract", "status"], name="idx_vt_spot_status"),
        ),
        migrations.AddIndex(
            model_name="volumetrapmonitor",
            index=models.Index(fields=["market_type", "status"], name="idx_vt_market_type_status"),
        ),
    ]
