# Generated by Django 4.2.8 on 2025-12-26 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("volume_trap", "0002_add_spot_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, verbose_name="统计名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="描述")),
                (
                    "market_type",
                    models.CharField(
                        blank=True,
                        help_text="all表示全部",
                        max_length=20,
                        null=True,
                        verbose_name="市场类型",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        blank=True,
                        help_text="all表示全部",
                        max_length=10,
                        null=True,
                        verbose_name="K线周期",
                    ),
                ),
                (
                    "status_filter",
                    models.CharField(
                        blank=True,
                        help_text="逗号分隔的状态列表",
                        max_length=50,
                        null=True,
                        verbose_name="状态筛选",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="开始日期")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="结束日期")),
                ("holding_bars", models.IntegerField(default=20, verbose_name="持仓K线数")),
                ("total_trades", models.IntegerField(default=0, verbose_name="总交易数")),
                ("profitable_trades", models.IntegerField(default=0, verbose_name="盈利交易数")),
                ("losing_trades", models.IntegerField(default=0, verbose_name="亏损交易数")),
                (
                    "win_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="胜率"
                    ),
                ),
                (
                    "avg_profit_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="平均收益率",
                    ),
                ),
                (
                    "max_profit_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最大单笔收益",
                    ),
                ),
                (
                    "min_profit_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最小单笔收益",
                    ),
                ),
                (
                    "total_profit_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="总收益率",
                    ),
                ),
                (
                    "avg_max_drawdown",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="平均最大回撤",
                    ),
                ),
                (
                    "worst_drawdown",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最差回撤",
                    ),
                ),
                (
                    "avg_bars_to_lowest",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="平均到达最低点K线数",
                    ),
                ),
                (
                    "profit_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="盈亏比",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "回测统计",
                "verbose_name_plural": "回测统计",
                "db_table": "volume_trap_backtest_statistics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=50, verbose_name="交易对")),
                (
                    "interval",
                    models.CharField(db_index=True, max_length=10, verbose_name="K线周期"),
                ),
                (
                    "market_type",
                    models.CharField(db_index=True, max_length=20, verbose_name="市场类型"),
                ),
                ("entry_time", models.DateTimeField(db_index=True, verbose_name="入场时间")),
                (
                    "entry_price",
                    models.DecimalField(decimal_places=8, max_digits=20, verbose_name="入场价格"),
                ),
                (
                    "lowest_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最低点时间"),
                ),
                (
                    "lowest_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="最低价格",
                    ),
                ),
                (
                    "bars_to_lowest",
                    models.IntegerField(blank=True, null=True, verbose_name="到达最低点K线数"),
                ),
                (
                    "max_profit_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="做空视角：(entry_price - lowest_price) / entry_price * 100",
                        max_digits=10,
                        null=True,
                        verbose_name="最大盈利百分比",
                    ),
                ),
                ("has_rebound", models.BooleanField(default=False, verbose_name="是否有反弹")),
                (
                    "rebound_high_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="反弹最高价",
                    ),
                ),
                (
                    "rebound_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="(rebound_high - lowest_price) / lowest_price * 100",
                        max_digits=10,
                        null=True,
                        verbose_name="反弹幅度百分比",
                    ),
                ),
                (
                    "max_drawdown_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="做空视角：持仓期间价格上涨导致的最大浮亏",
                        max_digits=10,
                        null=True,
                        verbose_name="最大回撤百分比",
                    ),
                ),
                ("exit_time", models.DateTimeField(blank=True, null=True, verbose_name="出场时间")),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="出场价格",
                    ),
                ),
                (
                    "final_profit_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="(entry_price - exit_price) / entry_price * 100",
                        max_digits=10,
                        null=True,
                        verbose_name="最终收益率",
                    ),
                ),
                (
                    "is_profitable",
                    models.BooleanField(blank=True, null=True, verbose_name="是否盈利"),
                ),
                (
                    "holding_bars",
                    models.IntegerField(
                        default=20, help_text="回测时的持仓周期设置", verbose_name="持仓K线数"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待回测"),
                            ("completed", "已完成"),
                            ("insufficient_data", "数据不足"),
                            ("error", "回测错误"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="回测状态",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "monitor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_result",
                        to="volume_trap.volumetrapmonitor",
                        verbose_name="关联监控记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "回测结果",
                "verbose_name_plural": "回测结果",
                "db_table": "volume_trap_backtest_result",
                "ordering": ["-entry_time"],
                "indexes": [
                    models.Index(fields=["status", "-entry_time"], name="idx_bt_status_entry"),
                    models.Index(fields=["symbol", "interval"], name="idx_bt_symbol_interval"),
                    models.Index(fields=["is_profitable"], name="idx_bt_profitable"),
                ],
            },
        ),
    ]
