# Generated by Django 4.2.8 on 2025-12-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volume_trap", "0003_create_backtest_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backtestresult",
            name="holding_bars",
        ),
        migrations.RemoveField(
            model_name="backteststatistics",
            name="holding_bars",
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="observation_bars",
            field=models.IntegerField(
                default=0, help_text="观察的K线数，0表示观察全部历史数据", verbose_name="观察K线数"
            ),
        ),
        migrations.AddField(
            model_name="backteststatistics",
            name="observation_bars",
            field=models.IntegerField(default=0, verbose_name="观察K线数"),
        ),
    ]
