# Generated by Django 4.2.8 on 2025-11-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='如: BTCUSDT, ETHUSDT', max_length=20, verbose_name='交易对')),
                ('interval', models.CharField(db_index=True, help_text='如: 1h, 4h, 1d', max_length=10, verbose_name='时间周期')),
                ('open_time', models.DateTimeField(db_index=True, verbose_name='开盘时间')),
                ('close_time', models.DateTimeField(verbose_name='收盘时间')),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='开盘价')),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='最高价')),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='最低价')),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='收盘价')),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='成交量')),
                ('quote_volume', models.DecimalField(decimal_places=8, help_text='Quote asset volume', max_digits=30, verbose_name='成交额')),
                ('trade_count', models.IntegerField(default=0, verbose_name='成交笔数')),
                ('taker_buy_volume', models.DecimalField(decimal_places=8, default=0, max_digits=30, verbose_name='主动买入量')),
                ('taker_buy_quote_volume', models.DecimalField(decimal_places=8, default=0, max_digits=30, verbose_name='主动买入额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'K线数据',
                'verbose_name_plural': 'K线数据列表',
                'db_table': 'backtest_kline',
                'ordering': ['symbol', 'interval', 'open_time'],
                'indexes': [models.Index(fields=['symbol', 'interval', 'open_time'], name='backtest_kl_symbol_ab8550_idx'), models.Index(fields=['symbol', 'interval', '-open_time'], name='backtest_kl_symbol_4280dc_idx'), models.Index(fields=['open_time'], name='backtest_kl_open_ti_798a0c_idx')],
                'unique_together': {('symbol', 'interval', 'open_time')},
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='回测名称')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='交易对')),
                ('interval', models.CharField(max_length=10, verbose_name='时间周期')),
                ('start_date', models.DateTimeField(verbose_name='开始日期')),
                ('end_date', models.DateTimeField(verbose_name='结束日期')),
                ('strategy_params', models.JSONField(help_text='包含: grid_step_pct, grid_levels, order_size, stop_loss等', verbose_name='策略参数')),
                ('initial_cash', models.DecimalField(decimal_places=2, default=10000, max_digits=20, verbose_name='初始资金')),
                ('final_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='最终价值')),
                ('total_return', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='总收益率')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='夏普比率')),
                ('max_drawdown', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='最大回撤')),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='胜率')),
                ('total_trades', models.IntegerField(default=0, verbose_name='总交易次数')),
                ('profitable_trades', models.IntegerField(default=0, verbose_name='盈利交易次数')),
                ('losing_trades', models.IntegerField(default=0, verbose_name='亏损交易次数')),
                ('equity_curve', models.JSONField(blank=True, help_text='时间序列的账户价值', null=True, verbose_name='权益曲线')),
                ('trades_detail', models.JSONField(blank=True, help_text='每笔交易的详细信息', null=True, verbose_name='交易明细')),
                ('daily_returns', models.JSONField(blank=True, null=True, verbose_name='每日收益')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '回测结果',
                'verbose_name_plural': '回测结果列表',
                'db_table': 'backtest_result',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'interval', '-created_at'], name='backtest_re_symbol_66213a_idx'), models.Index(fields=['-total_return'], name='backtest_re_total_r_b348f6_idx')],
            },
        ),
    ]
