# Generated by Django 4.2.8 on 2025-11-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_level', models.CharField(help_text='support_1 或 support_2', max_length=20, verbose_name='买入层级')),
                ('buy_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='买入价格')),
                ('buy_time', models.DateTimeField(verbose_name='买入时间')),
                ('buy_amount', models.DecimalField(decimal_places=8, help_text='币的数量', max_digits=20, verbose_name='买入数量')),
                ('buy_cost', models.DecimalField(decimal_places=2, help_text='USDT，含手续费', max_digits=20, verbose_name='买入成本')),
                ('buy_zone_weight', models.DecimalField(decimal_places=4, help_text='0.05-1.0', max_digits=5, verbose_name='买入权重')),
                ('sell_target_r1_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='R1目标价')),
                ('sell_target_r1_pct', models.DecimalField(decimal_places=2, help_text='百分比，如50.00表示50%', max_digits=5, verbose_name='R1分配比例')),
                ('sell_target_r1_sold', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='R1已卖数量')),
                ('sell_target_r1_zone_low', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='R1区间下界')),
                ('sell_target_r1_zone_high', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='R1区间上界')),
                ('sell_target_r2_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='R2目标价')),
                ('sell_target_r2_pct', models.DecimalField(decimal_places=2, help_text='百分比，如50.00表示50%', max_digits=5, verbose_name='R2分配比例')),
                ('sell_target_r2_sold', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='R2已卖数量')),
                ('sell_target_r2_zone_low', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='R2区间下界')),
                ('sell_target_r2_zone_high', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='R2区间上界')),
                ('total_sold_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='总已卖数量')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='扣除手续费后', max_digits=20, verbose_name='总卖出收入')),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='净利润')),
                ('status', models.CharField(choices=[('open', '持仓中'), ('partial', '部分平仓'), ('closed', '已平仓')], default='open', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('backtest_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_positions', to='backtest.backtestresult', verbose_name='所属回测')),
            ],
            options={
                'verbose_name': '网格持仓V2',
                'verbose_name_plural': '网格持仓列表V2',
                'db_table': 'grid_position_v2',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['backtest_result', 'status'], name='grid_positi_backtes_7a9f8b_idx'), models.Index(fields=['buy_level', 'status'], name='grid_positi_buy_lev_a4cb42_idx')],
            },
        ),
    ]
