# Generated by Django 4.2.8 on 2025-11-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_gridposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridposition',
            name='stop_loss_price',
            field=models.DecimalField(decimal_places=8, default=0, help_text='买入时的S2下界 × (1 - 止损%)，固定值', max_digits=20, verbose_name='止损价格'),
        ),
    ]
