# Generated by Django 4.2.8 on 2025-12-01 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0003_add_stop_loss_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='K线时间')),
                ('kline_index', models.IntegerField(verbose_name='K线索引')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='当前价格')),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='现金余额')),
                ('total_value', models.DecimalField(decimal_places=2, help_text='现金 + 持仓市值', max_digits=20, verbose_name='总价值')),
                ('grid_levels', models.JSONField(blank=True, help_text='\n        {\n            "support_2": {"price": 3100.0, "zone_low": 3098.0, "zone_high": 3102.0},\n            "support_1": {"price": 3270.0, "zone_low": 3268.0, "zone_high": 3272.0},\n            "resistance_1": {"price": 3740.0, "zone_low": 3738.0, "zone_high": 3742.0},\n            "resistance_2": {"price": 3910.0, "zone_low": 3908.0, "zone_high": 3912.0}\n        }\n        ', null=True, verbose_name='网格层级')),
                ('positions', models.JSONField(default=list, help_text='\n        [\n            {\n                "id": 1,\n                "buy_level": "support_1",\n                "buy_price": 3271.33,\n                "buy_amount": 0.0644,\n                "stop_loss_price": 3008.18,\n                "r1_target": 3593.56,\n                "r1_sold_pct": 0.0,\n                "r2_target": 3758.76,\n                "r2_sold_pct": 0.0,\n                "status": "open"\n            }\n        ]\n        ', verbose_name='持仓列表')),
                ('events', models.JSONField(default=list, help_text='\n        [\n            {\n                "type": "buy",\n                "position_id": 1,\n                "price": 3271.33,\n                "amount": 0.0644,\n                "cost": 210.80\n            },\n            {\n                "type": "sell",\n                "position_id": 13,\n                "target": "resistance_1",\n                "price": 2448.45,\n                "amount": 0.0027,\n                "revenue": 6.65\n            },\n            {\n                "type": "stop_loss",\n                "position_ids": [9, 10, 11],\n                "price": 2527.12,\n                "total_revenue": 455.29\n            }\n        ]\n        ', verbose_name='事件列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('backtest_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='backtest.backtestresult', verbose_name='所属回测')),
            ],
            options={
                'verbose_name': '回测快照',
                'verbose_name_plural': '回测快照列表',
                'db_table': 'backtest_snapshot',
                'ordering': ['backtest_result', 'kline_index'],
                'indexes': [models.Index(fields=['backtest_result', 'kline_index'], name='backtest_sn_backtes_2d6d73_idx'), models.Index(fields=['backtest_result', 'timestamp'], name='backtest_sn_backtes_c2c270_idx')],
                'unique_together': {('backtest_result', 'kline_index')},
            },
        ),
    ]
