# Generated by Django 4.2.8 on 2025-12-01 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0004_backtestsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], db_index=True, max_length=10, verbose_name='挂单类型')),
                ('grid_level', models.CharField(db_index=True, help_text='support_1, support_2, resistance_1, resistance_2', max_length=20, verbose_name='网格层级')),
                ('target_price', models.DecimalField(decimal_places=8, help_text='买入/卖出的目标价格', max_digits=20, verbose_name='挂单价格')),
                ('zone_low', models.DecimalField(decimal_places=8, help_text='网格区间的下界', max_digits=20, verbose_name='区间下界')),
                ('zone_high', models.DecimalField(decimal_places=8, help_text='网格区间的上界', max_digits=20, verbose_name='区间上界')),
                ('locked_amount_usdt', models.DecimalField(decimal_places=2, default=0, help_text='锁定的USDT金额（买单）', max_digits=20, verbose_name='锁定金额USDT')),
                ('locked_amount_crypto', models.DecimalField(decimal_places=8, default=0, help_text='锁定的币数量（卖单）', max_digits=20, verbose_name='锁定币数量')),
                ('created_time', models.DateTimeField(db_index=True, verbose_name='创建时间')),
                ('expire_time', models.DateTimeField(db_index=True, verbose_name='过期时间')),
                ('filled_time', models.DateTimeField(blank=True, null=True, verbose_name='成交时间')),
                ('status', models.CharField(choices=[('pending', '挂单中'), ('filled', '已成交'), ('expired', '已过期'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='挂单状态')),
                ('fund_status', models.CharField(choices=[('locked', '资金已锁定'), ('released', '资金已释放')], db_index=True, default='locked', max_length=20, verbose_name='资金状态')),
                ('filled_price', models.DecimalField(blank=True, decimal_places=8, help_text='实际成交价格', max_digits=20, null=True, verbose_name='成交价')),
                ('filled_amount', models.DecimalField(blank=True, decimal_places=2, help_text='实际成交金额', max_digits=20, null=True, verbose_name='成交金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('backtest_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_orders', to='backtest.backtestresult', verbose_name='回测结果')),
                ('created_position', models.ForeignKey(blank=True, help_text='买单成交后创建的仓位', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_order', to='backtest.gridposition', verbose_name='创建的仓位')),
                ('locked_position', models.ForeignKey(blank=True, help_text='卖单锁定的仓位', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_orders', to='backtest.gridposition', verbose_name='锁定仓位')),
            ],
            options={
                'verbose_name': '挂单记录',
                'verbose_name_plural': '挂单记录列表',
                'db_table': 'backtest_pending_order',
                'ordering': ['backtest_result', 'created_time'],
                'indexes': [models.Index(fields=['backtest_result', 'status', 'fund_status'], name='backtest_pe_backtes_598fce_idx'), models.Index(fields=['backtest_result', 'order_type', 'status'], name='backtest_pe_backtes_4d69ee_idx'), models.Index(fields=['backtest_result', 'grid_level', 'status'], name='backtest_pe_backtes_6d4390_idx'), models.Index(fields=['expire_time'], name='backtest_pe_expire__e2e71c_idx')],
            },
        ),
    ]
