# Generated by Django 4.2.8 on 2025-12-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0006_add_enhanced_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridposition',
            name='direction',
            field=models.CharField(choices=[('long', '多单'), ('short', '空单')], default='long', help_text='long=多单（做多），short=空单（做空）', max_length=10, verbose_name='交易方向'),
        ),
        migrations.AlterField(
            model_name='gridposition',
            name='buy_level',
            field=models.CharField(help_text='support_1 或 support_2（多单）；resistance_1 或 resistance_2（空单）', max_length=20, verbose_name='买入层级'),
        ),
    ]
