# Generated by Django 4.2.8 on 2025-12-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtest", "0007_add_position_direction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kline",
            options={
                "ordering": ["symbol", "interval", "market_type", "open_time"],
                "verbose_name": "K线数据",
                "verbose_name_plural": "K线数据列表",
            },
        ),
        migrations.AlterUniqueTogether(
            name="kline",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="kline",
            name="market_type",
            field=models.CharField(
                choices=[("spot", "现货"), ("futures", "合约")],
                default="futures",
                help_text="现货或合约市场类型",
                max_length=20,
                verbose_name="市场类型",
            ),
        ),
        migrations.AlterField(
            model_name="kline",
            name="symbol",
            field=models.CharField(
                db_index=True,
                help_text="如: BTCUSDT（合约）, BTC/USDT（现货）",
                max_length=20,
                verbose_name="交易对",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kline",
            unique_together={("symbol", "interval", "market_type", "open_time")},
        ),
        migrations.AddIndex(
            model_name="kline",
            index=models.Index(
                fields=["market_type", "symbol", "interval"], name="backtest_kl_market__ae03b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kline",
            index=models.Index(
                fields=["market_type", "-open_time"], name="backtest_kl_market__359099_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kline",
            index=models.Index(
                fields=["symbol", "interval", "market_type", "-open_time"],
                name="backtest_kl_symbol_cdb92c_idx",
            ),
        ),
    ]
